Make gles work when not specifying version
rust-windowing/glutin pull request #1289
Opened 2020-03-29 13:21 UTC by derekdreery

This PR makes glutin work with GLES when a requested version is not given. I think ignoring the version is ok because we don't know it until we try to create a context. I've copied the oldest gles version code to be conservative.

- [ ] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users

2020-03-29 13:31 UTC, derekdreery commented
The test failure is spurious I think.

2020-04-12 16:04 UTC, derekdreery commented
ping

2022-04-29 10:17 UTC, kchibisov requested changes
Could also add changelog entry for that. If you're not interested in that patch I could take care of it...

2022-04-29 10:17 UTC, kchibisov commented on glutin/src/api/egl/mod.rs
> +            (Api::OpenGlEs, None) => {
It seems like you can merge it with previous match arm?

2022-05-02 13:29 UTC, derekdreery commented
Hi @kchibisov would you mind finishing the patch - I've forgotten what I did it for. If there's an issue with you doing it I'd still be happy to, but probably easier for you.

2022-05-04 21:26 UTC, kchibisov commented
Closing in favor of #1404.

2022-05-04 21:26 UTC, closed without merging