Make x11 and wayland features
rust-windowing/glutin pull request #1329
Opened 2020-10-03 13:11 UTC by ogoffart

winit now has a x11 and wayland feature that can be used to disable one of them, make uses of these feature also in this crate.

My goal is to reduce binary size of my binaries that does not use wayland.

- [X] Tested on all platforms changed
- [X] Compilation warnings were addressed  (i made sure not to introduce new warnings)
- [X] `cargo fmt` has been run on this branch
- [X] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

2020-10-03 16:39 UTC, chrisduerr requested changes

2020-10-03 16:39 UTC, chrisduerr commented on glutin/Cargo.toml
> +winit = { version="0.23.0", default-features = false }
```suggestion
winit = { version = "0.23.0", default-features = false }
```

2020-10-03 16:39 UTC, chrisduerr commented on glutin/src/platform_impl/unix/mod.rs
>  mod wayland;
For things like glx you define the feature inside the module while defining it outside the module here. Would probably be best to be consistent. I generally prefer having it as external annotation at the top of the module.

2020-10-04 15:38 UTC, chrisduerr requested changes

2020-10-04 15:38 UTC, chrisduerr commented on glutin/src/platform_impl/unix/mod.rs
> +        unreachable!()
This is **not** unreachable.

2020-10-04 15:38 UTC, chrisduerr commented on glutin/src/platform_impl/unix/mod.rs
> +        unreachable!()
This is **not** unreachable.

2020-10-05 05:01 UTC, ogoffart commented on glutin/src/platform_impl/unix/mod.rs
> +        unreachable!()
Is it not?
I am under the impression that it was either x11 or wayland and that this should be unreachable.
I've added a if just for symmetry.  But   `is_x11()` is defined as `!is_wayland()`.
What are you suggesting to do instead?  Is a `panic!` better than a `unreachable!` ?

2020-10-05 07:57 UTC, chrisduerr commented on glutin/src/platform_impl/unix/mod.rs
> +        unreachable!()
What stops you from compiling it with neither x11 or wayland?

2020-10-05 08:14 UTC, ogoffart commented on glutin/src/platform_impl/unix/mod.rs
> +        unreachable!()
Right, this could happen if, for example, winit was compiled with wayland support (via another dependency), but glutin was not compiled with wayland support, and that we run on wayland anyway.

So the question is what do you think should happen in that case? `panic!("glutin was not compiled to support this backend")` ?

2020-10-05 08:20 UTC, chrisduerr commented on glutin/src/platform_impl/unix/mod.rs
> +        unreachable!()
I'd advocate for an error during compilation, not runtime. See https://doc.rust-lang.org/std/macro.compile_error.html.

2020-10-06 18:37 UTC, chrisduerr requested changes

2020-10-06 18:37 UTC, chrisduerr commented on glutin/src/platform_impl/unix/mod.rs
> +        panic!("Unsupported backend")
Now unreachable would have been the correct choice! Since it should be actually unreachable now. Though I think you can still pass messages to it so feel free to add the "at least one of.." message there too. But just unreachable should be fine too.

2020-10-06 20:30 UTC, ogoffart commented on glutin/src/platform_impl/unix/mod.rs
> +        panic!("Unsupported backend")
I just tested that and it is possible to reach this if the winit backend is compiled with more features:

To reproduce, imagine this in the application's Carto.toml
```
winit = { version = "0.23" }  # default feature enabled so wayland is enabled when building winit
glutin = { version = "0.25.0", default-features = false, feature="x11"}
```
And then run the resulting program  on wayland

2020-10-06 20:41 UTC, chrisduerr requested changes

2020-10-06 20:41 UTC, chrisduerr commented on glutin/src/platform_impl/unix/mod.rs
> +        panic!("Unsupported backend")
Ah, because at that point you're running into a runtime check, yeah.

I'd like to print a more specific error though, since `Unsupported backend` is far too generic to be helpful. Maybe something more like `glutin was not compiled with support for this display server`, just as a rough suggestion. Maybe that's a bit long.

2020-10-07 11:47 UTC, chrisduerr approved these changes
Thanks for your contribution.

@kchibisov Do you know of anyone else who can review this? Could you maybe check that Wayland still works at least? Otherwise I'd just merge it myself.

2020-10-07 13:00 UTC, kchibisov commented
>@kchibisov Do you know of anyone else who can review this? Could you maybe check that Wayland still works at least? Otherwise I'd just merge it myself.

I'm not aware that anyone can review this, however given that it's basically adding a bunch of cfg's anyone can review it. it works on Wayland, so if it works on X11 (can't test it right now). You're free to merge it.

2020-10-07 14:22 UTC, merged