Fix possible panic on Windows for headless contexts because of active drag and drop
rust-windowing/glutin pull request #1352
Opened 2021-05-11 08:46 UTC by haraldreingruber-dedalus

Integrating a headless context into a legacy Windows application was not working for me because of this error:

> thread 'unnamed' panicked at 'OleInitialize failed! Result was: `RPC_E_CHANGED_MODE`. Make sure other crates are not using multithreaded COM library on the same thread or disable drag and drop support.',…\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.24.0\src\platform_impl\windows\window.rs:85:25

I guess a headless context usually doesn't need drag-and-drop support, so it should be safe to disable this default winit behavior?

Looking forward to your thoughts!

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

2021-06-15 09:10 UTC, haraldreingruber-dedalus commented
Is there anything I can improve to get this merged?

2021-06-25 08:30 UTC, maroider requested changes
> Is there anything I can improve to get this merged?

There isn't much of anything like that, tbh.
It's more a matter of "no one other than me seems to be actively merging PRs at the moment", and I'm not the "right guy" to maintain glutin for any length of time, really.

Fortunately for you, I'm familiar with this issue, so I feel somewhat comfortable merging this.

2021-06-25 08:30 UTC, maroider commented on CHANGELOG.md
> +- Fixed possible panic (OleInitialize failed! Result was: `RPC_E_CHANGED_MODE`) for headless contexts on Windows because of active drag-and-drop
```suggestion
- On Windows, fixed a panic for headless contexts because of active drag-and-drop (OleInitialize failed! Result was: `RPC_E_CHANGED_MODE`)
```

2021-06-25 11:43 UTC, haraldreingruber-dedalus commented
> Fortunately for you, I'm familiar with this issue, so I feel somewhat comfortable merging this.

Awesome, thanks for your improvement suggestions for the changelog!

2021-06-25 11:44 UTC, maroider approved these changes

2021-06-26 13:14 UTC, merged