Ignore vsync safely on unsupported platforms.
rust-windowing/glutin pull request #1395
Opened 2022-04-15 10:39 UTC by Ar37-rs

- [✅] Tested on all platforms changed
- [✅] Compilation warnings were addressed
- [✅] `cargo fmt` has been run on this branch
- [✅] `cargo doc` builds successfully
- [✅] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
improvement of this PR: https://github.com/rust-windowing/glutin/pull/1387
thanks to: @ch-sy

2022-04-15 10:46 UTC, Ar37-rs commented
it really useful for anyone like myself who's running their GL apps on software render mode (e.g: mesa llvmpipe) on their VM, so the next version of glutin there will be no more such thing as this issue anymore https://github.com/rust-windowing/glutin/issues/1393
thank you @kchibisov

2022-04-15 10:49 UTC, kchibisov requested changes

2022-04-15 10:49 UTC, kchibisov commented on glutin/src/api/glx/mod.rs
> +            eprintln!("Couldn't find any available vsync extension on this platform.")
Should we `log` it?

I'm also not sure if we've asked for `vsync`?

I think you want to have some fallback, right? Could change API `with_vsync(Option<bool>)`, and when passing `None` it means you don't care about whether vsync is used or not?

2022-04-15 10:58 UTC, Ar37-rs commented on glutin/src/api/glx/mod.rs
> +            eprintln!("Couldn't find any available vsync extension on this platform.")
exactly, for fallback purpose.  on third party apps the end user have no control over. like egui for example, it uses vsync by default, and there's no way to change the fallback config on the fly. if the GPU doesn't support vsync the apps will be crashing like so many issue has been occured like this: https://github.com/rust-windowing/glutin/issues/1393

2022-04-15 11:19 UTC, Ar37-rs commented on glutin/src/api/glx/mod.rs
> +            eprintln!("Couldn't find any available vsync extension on this platform.")
@kchibisov After this PR being merged i believe this issue: https://github.com/rust-windowing/glutin/issues/1034  can be closed also.

2022-04-15 11:30 UTC, kchibisov commented on glutin/src/api/glx/mod.rs
> +            eprintln!("Couldn't find any available vsync extension on this platform.")
As I said, would you mind changing the API to `Option<bool>`? I think it'll make sense for the time being, since some applications want to force vsync.

2022-04-15 11:37 UTC, Ar37-rs commented on glutin/src/api/glx/mod.rs
> +            eprintln!("Couldn't find any available vsync extension on this platform.")
there's no need to change bool to Option<bool>, because the logic uses statement if {..} else if {..}. so if the GPU driver support the vsync extension it will use vsync, otherwise the error will be printed

2022-04-15 13:35 UTC, Ar37-rs commented
@kchibisov if i changed the bool to ```Option<bool>``` obviously it will be breaking change, and i don't want to do that since the only issue which cause the apps with glutin dependecies crashing so often is that the current version of glutin inability to ignore vsync on the machine with no HW acceleration support. after modified glutin the same as on this PR i swear i've tested on windows with Intel GPU HW acceleration and linux with software render (llvmpipe). both are working fine, no more crashing even on software render mode unless with a specific GL option, let's say using glow crate with multisampling > 4 (of course, software render can't comprehend pixelFormat with multisampling large than that). and GPU HW acceleration there's no issue at all, thank you. @kchibisov would you mind to merge this PR? otherwise i'll close this myself.

2022-04-15 15:22 UTC, closed without merging

2022-04-19 21:58 UTC, kchibisov commented
>@kchibisov if i changed the bool to Option<bool> obviously it will be breaking change

I'm fine with doing breaking change, given that the next winit release is a glutin breaking change anyway, so given that the next release will be breaking anyway, I'm all for adding that kind of API.