Return Err instead of panic on surfaceless GLX contexts on Linux
rust-windowing/glutin pull request #1397
Opened 2022-04-16 19:14 UTC by unlimitedbacon

Returns an `Err` instead of panicking in this specific case when surfaceless context creation fails on Linux. This allows my program to gracefully fall back to an OsMesa context when it fails.

- [x] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

2022-04-29 10:01 UTC, kchibisov requested changes
Could you add changelog entry and run rustfmt. Other than that it should be good to go.

2022-05-10 06:16 UTC, unlimitedbacon commented
Done

2022-05-26 21:40 UTC, kchibisov approved these changes

2022-05-26 21:43 UTC, MarijnS95 approved these changes

2022-05-27 14:11 UTC, merged