Run clippy in the CI with warnings disallowed; address most warnings
rust-windowing/glutin pull request #1412
Opened 2022-05-28 16:18 UTC by MarijnS95

This is a draft mainly to look at how `cargo clippy --fix` and myself have addressed warnings for most issues. There are still a few remaining, and clippy found some odd/fishy things we should look into.

- [ ] Tested on all platforms changed
- [ ] Compilation warnings were addressed
- [ ] `cargo fmt` has been run on this branch
- [ ] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

2022-05-28 16:21 UTC, MarijnS95 commented on glutin_examples/examples/sharing.rs
> -    std::mem::drop(windowed_context);
Clippy points out here that all these `mem::drop`s on the result of `get_current()` are useless, because that function returns borrows. Dropping a borrow has no effect. Now, with this borrow gone, `clippy` complains about some unused `let` bindings so we should see if the function call itself is just "getting" something or if it's really doing something under the hood of which the result somehow needs to be "kept alive".

2022-05-28 16:28 UTC, MarijnS95 commented on glutin/src/api/glx/mod.rs
> +use std::ops::{Deref, DerefMut};
Clippy didn't like the submodule here being named the same as the containing module, and I don't see any reason for it to exist. Perhaps I should reorder the `use` statements to all be at the top of the file, perhaps a subsequent PR on top that cleans up everything automatically once using `cargo fmt -- --config imports_granularity=crate --config group_imports=stdexternalcrate`? Let me know if that's okay and/or we should pick different settings for it.

2022-05-28 16:29 UTC, MarijnS95 commented on glutin/src/api/egl/mod.rs
> +use std::sync::{Arc, Mutex};
Same here, I didn't see a need for this submodule to exist besides the use of `std::sync::Mutex` within versus `parking_lot::Mutex` outside. Same question applies regarding moving (preferably though `cargo fmt -- --config imports_granularity=crate --config group_imports=stdexternalcrate`) imports back together.

2022-05-29 11:55 UTC, kchibisov commented on glutin/src/api/glx/mod.rs
> +use std::ops::{Deref, DerefMut};
>cargo fmt -- --config imports_granularity=crate --config group_imports=stdexternalcrate? Let me know if that's okay and/or we should pick different settings for it.

In general I'd change the whole formatting for glutin/winit all together, given that it's hard to read code with rustfmt defaults. Though, lots of good options are not available on stable rustfmt and requires nightly for it...

In general the entire glutin should be rewritten to be decoupled from winit, but it's another long story...

2022-05-29 12:48 UTC, MarijnS95 commented on glutin/src/api/glx/mod.rs
> +use std::ops::{Deref, DerefMut};
In contrary, I've always found `rustfmt` code with the defaults extremely pleasant to read, especially in contrast to the horrible abomination `clang-format` usually comes up with for C/C++ code. Yes, it is a pain that we cannot use `rustfmt` to automatically regroup and recombine `use` statements on `stable`, but it's "coming™" at least.

So the question is basically, should we:
- Reformat it just once with this command;
- Force this formatting in the CI, even if contributors can't easily reproduce it locally;
- Don't do anything for now.

I don't think it matters what `winit` does, I'm contributing to `glutin` here and now and am not looking at `winit` code for the time being :) - we can tackle that another day unless you feel like both projects should do things in unison (which I doubt, given that you want to _decouple it_).

One important mention: these features are unstable and don't work in `rustfmt.toml` yet. _However_, on a stable Rust toolchain they _do_ work when passed on the commandline as showcased above. There's still the warning that it's `only available in nightly channel`, but it works :shrug:

2022-05-29 12:50 UTC, MarijnS95 commented on glutin/src/api/glx/mod.rs
> +use std::ops::{Deref, DerefMut};
One more comment on decoupling: that's exactly what I'll need to support "random" `Surface`s in `glutin`, without a window loop nor events (ie. #1324). I think I can make it work, but it's odd to have the `winit` dependency and usage chained through the API at that point. Perhaps rewriting it in a more layered system would help, but that's for another issue.

2022-05-29 13:00 UTC, kchibisov commented on glutin/src/api/glx/mod.rs
> +use std::ops::{Deref, DerefMut};
I'd suggest to look into https://github.com/rust-windowing/glutin/tree/v0.23_reworks. It should have like the most of the thing done iirc. just the author and the past maintainer disappeared...

But we can pick up that branch and try moving forward with it, given that glutin didn't had that much changes and most can ported to it without much issues.

If you feel like, I think I can pick up that rework, though, I'm not sure I'll move forward that much with macOS/Windows bits, but at least we can try...

2022-05-29 13:01 UTC, kchibisov commented on glutin/src/api/glx/mod.rs
> +use std::ops::{Deref, DerefMut};
>In contrary, I've always found rustfmt code with the defaults extremely pleasant to read

The defaults are probably nice, however I like it more with `use_small_heuristics = "Max"`. Since it's less lines of code to read and having one liners is easier for me to grasp other than 5 lines of basically `.ok()` lines.

2022-05-29 21:01 UTC, MarijnS95 commented on glutin/src/api/glx/mod.rs
> +use std::ops::{Deref, DerefMut};
@kchibisov Just a heads-up that I don't use OpenGL/EGL, but rolled into the maintainer role of `android-ndk-rs` some time ago and kept getting overloaded with strange attempts to fix "glutin not compiling for Android" in strange ways on the ndk/winit side (ie. adding unimplemented callback interfaces just to make things compile, not speaking of working just yet - why not fix it in glutin :shrug:).

Now I've taken it upon myself to fix this situation and close a significant amount of issues and stale PRs.

With that come a few drive-by fixes like addressing all `clippy` lints and rolling them up into the CI, to make my own development/contributing experience a little nicer. We'll get Android added to the CI when open PR(s, #1411) land too, so that it doesn't invisibly break in the future.

---

As such I'd love for you to pick up the rework as a more active maintainer. I'll probably stick around to aid on Android-specific issues, but I don't think supporting "window-less" surface support (#1324) are undoable before such a rework lands (so no hurry!).

---

> The defaults are probably nice, however I like it more with `use_small_heuristics = "Max"`. Since it's less lines of code to read and having one liners is easier for me to grasp other than 5 lines of basically `.ok()` lines.

I hadn't really thought about that one, but yes this has been annoying me on some occasions. `rustfmt` isn't absolutely perfect and I'll keep this one in mind, thanks for bringing it to my attention :+1:

2022-06-05 15:30 UTC, MarijnS95 commented
Looks like `nightly` clippy is throwing some false-positives on `objc::msg_send![]`'s return-type annotation https://docs.rs/objc/latest/objc/#messaging-objects.

That raises the question: is it desired to run `nightly` clippy? I'm personally all in favour of having `clippy` in the CI (some call it low signal-to-noise ratio, I find it making the code more pleasant to read), but `nightly` clippy is a bit overzealous. It has a high amount of false-positives compared to the actual future-proofing one might get; better wait for the stabilized version.

So for now this PR will only run `stable` clippy :)

2022-06-05 15:45 UTC, kchibisov commented
Running on nightly doesn't make much sense, except if the target requires nightly for whatever reason. Just stable is enough, I guess.

2022-06-05 15:46 UTC, MarijnS95 commented
Doing that now, and all checks succeed :tada: - what's your thought about getting the other PRs and this one in?

2022-06-05 16:48 UTC, kchibisov commented on glutin/src/api/ios/mod.rs
> +        // debug!("proc {} -> {:?}", proc_name, addr);
Can remove this.

2022-06-05 19:20 UTC, kchibisov approved these changes

2022-06-07 18:28 UTC, MarijnS95 commented on glutin_examples/examples/sharing.rs
> -    std::mem::drop(windowed_context);
I haven't been able to test this example yet, it fails to find any config in `eglChooseConfig` and I have yet to dissect what is going on/wrong :)

2022-06-07 19:10 UTC, kchibisov requested changes
Actually, could you add into lib.rs of each crate.
```rust
#![deny(clippy::all)
#![cfg_attr(feature = "cargo-clippy", deny(warnings))]
```
Instead of denying on CI?

2022-06-07 19:16 UTC, MarijnS95 commented
@kchibisov What would be the advantage of those annotations? I personally don't like disallowing all clippy warnings during development, it doesn't allow contributors to compile code when perhaps having one or two testing variables / functions commented out.

Secondly, what's the advantage of disallowing normal `rustc` warnings through a `cargo-clippy` feature? I don't think I've seen such a setup yet.

2022-06-07 19:22 UTC, kchibisov commented
>@kchibisov What would be the advantage of those annotations?

I mean that with those two you can compile normally, but when you run clippy everything errors out.

2022-06-08 07:26 UTC, MarijnS95 commented
> I mean that with those two you can compile normally, but when you run clippy everything errors out. The intention is to error out on clippy, while allowing checks/builds to throw warnings as usual.

Right, yes. I use `clippy` in `rust-analyzer` (to see `clippy` lints directly in my editor, instead of only `rustc` warnings) and it typically stops linting on the first crate that encounters errors (`deny`, `-Dwarnings`) meaning it was not working on `glutin_examples` until #1408/#1413 were addressed (both are `deny` lints).

Strangely enough it seems to be fine now, without those commits :shrug: 

> That's what we're using in alacritty for years. Basically it means: "when running clippy, treat all rustc warnings as errors".

Ack, understood. I have previously seen but forgot that `cargo-clippy` is an actual feature (not `cfg`) that's enabled inside crates when "compiling" code under `clippy`.

Do you mind if I leave `deny(clippy::all)` out? That group consists of warn/deny lints only, and is already unambiguously covered by `#![cfg_attr(feature = "cargo-clippy", deny(warnings))]`. For example:

`` note: `#[deny(clippy::missing_safety_doc)]` implied by `#[deny(warnings)]` ``

> Instead of denying on CI?

Do you mind if I leave this? In the hypothetical case that a new crate is added? Otherwise this should also be added to every binary (test/example) target.

2022-06-09 19:09 UTC, kchibisov commented
>Do you mind if I leave deny(clippy::all) out? That group consists of warn/deny lints only, and is already unambiguously covered by #![cfg_attr(feature = "cargo-clippy", deny(warnings))]. For example:

That's fine. You can go ahead.

2022-06-10 10:27 UTC, kchibisov commented
@MarijnS95 sharing is also failing for me. It could be failing that way for a long time on Wayland, and I won't be surprised. Not sure that we should bother with it here since it's not something new.

2022-06-10 10:34 UTC, MarijnS95 commented
@kchibisov Perfect, let's go for it then. If you can review this once more and approve it, I'll fix the conflict and re-push!

2022-06-10 10:39 UTC, kchibisov requested changes
Just a small nits I've found after re-review.

2022-06-10 10:39 UTC, kchibisov commented on glutin/src/api/egl/mod.rs
> +            let list = String::from_utf8(p.to_bytes().to_vec()).unwrap_or_else(|_| String::new());
```suggestion
            let list = String::from_utf8(p.to_bytes().to_vec()).unwrap_or_default();
```

2022-06-10 10:39 UTC, kchibisov commented on glutin/src/api/egl/mod.rs
> +            let list = String::from_utf8(p.to_bytes().to_vec()).unwrap_or_else(|_| String::new());
```suggestion
            let list = String::from_utf8(p.to_bytes().to_vec()).unwrap_or_default();
```

2022-06-10 11:15 UTC, MarijnS95 commented
Nice catch, I hadn't spotted that one in the automatic `clippy --fix` diff :)

2022-06-15 06:45 UTC, kchibisov approved these changes

2022-06-15 09:22 UTC, merged