Add Android example
rust-windowing/glutin pull request #1417
Opened 2022-06-05 16:17 UTC by MarijnS95

As mentioned in #1398/#1411 we should have an example that showcases how to deal with the Android activity lifecycle.  Ultimately this turns into a helper function on `ContextWrapper` that has access to the internal surface for recreation, as did the broken implementation prior to #1411.  At the same time I hope to replace `new_windowed()` with an implementation soon™ that takes a `RawWindowHandle`, making the code more generic, `winit`-agnostic, and allows users to use Android `Surface`s for specific views in their Java/Kotlin/Flutter apps without needing a fullscreen `NativeActivity`.

This PR is based on top of #1412 so that my editor doesn't go bonkers on all the lint warnings/errors :)

2022-06-05 16:18 UTC, MarijnS95 commented on glutin/src/api/egl/mod.rs
> +            (Api::OpenGlEs, None | Some((3, _))) => {
Not yet sure what to do about this, when requesting `Latest` instead of a specific version. Can/should we load the specific version from anywhere?

2022-06-05 16:19 UTC, MarijnS95 commented on glutin_examples/examples/android.rs
> +                    windowed_context.resize(size);
No-op on Android, not implemented for EGL.

2022-06-05 16:22 UTC, kchibisov commented on glutin_examples/examples/android.rs
> +                    windowed_context.resize(size);
What do you mean, we do have resize on egl, just on wayland or something like that.

2022-06-05 16:24 UTC, MarijnS95 commented on glutin_examples/examples/android.rs
> +                    windowed_context.resize(size);
It's not provided/implemented/needed in the EGL API, so Android implements this as `pub fn resize(&self, _: u32, _: u32) {}`.

2022-06-05 16:32 UTC, kchibisov commented on glutin_examples/examples/android.rs
> +                    windowed_context.resize(size);
Ok then. This api is purely for consistency with other platforms, X11 also doesn't have it.

2022-06-05 16:33 UTC, MarijnS95 commented on glutin_examples/examples/android.rs
> +                    windowed_context.resize(size);
Yep, as such I'm simply not sure if the example should call or omit it.

2022-06-12 17:55 UTC, MarijnS95 commented on README.md
> +Be sure to handle Android's lifecycle correctly when using a `winit` window by only creating a GL surface (currently entire context) after `winit` raises `Event::Resumed`, and destroy it again upon r
We should possibly reword this if/when https://github.com/rust-windowing/winit/pull/2331 lands.

2022-06-12 20:42 UTC, rib commented on glutin_examples/examples/android.rs
> +                    windowed_context.resize(size);
Wouldn't it be best, ideally, to aim for an example that demonstrates running on Android _and_ hopefully most/all other platforms too?

An Android example is mainly just necessary because, compared to other platforms, it has these extra fiddly details due to the surface view coming and going but ideally most people will just want to write portable code and not have to worry about the platform until they are doing something fundamentally platform specific.

2022-06-12 20:52 UTC, MarijnS95 commented on glutin_examples/examples/android.rs
> +                    windowed_context.resize(size);
That's the ideal case, but since we aren't there yet (i.e. your `winit` PR is just the beginning and I have more changes planned for `glutin`) this seems like the best temporary compromise.

Note that it also has some additional setup in `Cargo.toml` - but it breaks CI and I **thiiink** we can have a `crate-type = ["bin", "cdylib"]`.

This'll also help us toy around with reintroducing some helper API around `Suspended`/`Resumed` events that only recreate the GL Surface, instead of the entire EGL/GL Context.

2022-06-12 20:54 UTC, MarijnS95 commented on glutin_examples/examples/android.rs
> +                    windowed_context.resize(size);
Nope:

```console
$ cargo r -p glutin_examples --example android
error: example target `android` is a library and cannot be executed`
$ cargo apk r -p glutin_examples --example android
   Compiling glutin_examples v0.1.2 (glutin/glutin_examples)
error: cannot mix `bin` crate type with others

error: could not compile `glutin_examples` due to previous error
Error: Command `cargo build --target aarch64-linux-android -p glutin_examples --example android` had a non-zero exit code.
```

2022-06-15 09:33 UTC, MarijnS95 commented on glutin_examples/Cargo.toml
> +crate-type = ["cdylib"]
I've yet to figure out how to best solve the CI failure here:

```console
$ cargo $WEB test --no-run --verbose --target x86_64-apple-ios
error: cannot produce cdylib for `glutin_examples v0.1.2 (/Users/runner/work/glutin/glutin/glutin_examples)` as the target `x86_64-apple-ios` does not support these crate types
Error: Process completed with exit code 101.
```

2022-09-03 05:58 UTC, kchibisov commented
This would need update to the latest Api.

2022-09-06 18:58 UTC, MarijnS95 commented
@kchibisov Sure, I've just returned from holiday and am slowly getting back into things, here's hoping we can use this Android example to finally vet the API to be compatible/sensible in this regard.

Pieced together something that compiles at least, but running into ``thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { raw_code: None, raw_os_message: None, kind: BadConfig }', glutin_examples/examples/android.rs:54:73``, will throw some more time at this when it's light outside again.

2022-09-06 19:02 UTC, kchibisov commented
>Pieced together something that compiles at least, but running into thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { raw_code: None, raw_os_message: None, kind: BadConfig }', glutin_examples/examples/android.rs:54:73, will throw some more time at this when it's light outside again.

You should ask for GLES I guess in the template builder.

2022-09-06 19:11 UTC, MarijnS95 commented
@kchibisov Right, yes, I also had to add `.with_context_api(glutin::context::ContextApi::Gles(None))` (not sure why we have two places for this, I'm not too familiar with the GL(ES) startup/setup), it's rendering (clearing) a teal background now.

2022-09-06 19:17 UTC, kchibisov commented
@MarijnS95 could we use the same example as for desktop, but for android as well? I'll look into adjusting api here in that regard.

2022-09-06 19:26 UTC, MarijnS95 commented
@kchibisov That'd be nice, I copy-pasted the example from yours so it's almost identical, `#[cfg_attr(target_os = "android", ndk_glue::main(backtrace = "on"))]` already makes this a generic `fn main()` and `Resumed` is emitted on every platform now so we might get away with a single file. `crate-type = ["cdylib"]` will throw a spanner in the works, though.

2022-09-06 20:44 UTC, kchibisov commented
Yeah, if we can have a single example for each platform it could be better? But I'm not entirely sure? Maybe having a separate example for android works as well...

2022-09-06 22:22 UTC, MarijnS95 commented
@kchibisov I think we can, we already have the `glutin_example` crate-library provide `support`; the more code we move in there the smaller / less overlap remains in the desktop-runnable binary and Android-runnable library (apk).

2022-09-07 20:45 UTC, kchibisov commented
You should rebase and fix the CI. Be aware that formatting is on nightly.

2022-09-07 21:00 UTC, MarijnS95 commented
I'm aware, and was just waiting for the dependent PR to be merged before reevaluating where to take this.

2022-09-07 22:20 UTC, kchibisov requested changes
I'd suggest you to create context out side of `run`. We should advertise the best we can here. The problem is symbol loading, I guess? I wonder if we can make context current, but without any surface? Make add Api for that or something to help here.

2022-09-07 22:20 UTC, kchibisov commented on glutin_examples/examples/android.rs
> +    // TODO: On Android this is can only be retrieved _AFTER_ Event::Resumed, but
Would suggest to resolve this TODO since ti should be trivial.

2022-09-07 22:20 UTC, kchibisov commented on glutin_examples/examples/android.rs
> +        // .compatible_with_native_window(raw_window_handle)
Don't need that.

2022-09-07 22:20 UTC, kchibisov commented on glutin_examples/examples/android.rs
> +        .with_surface_type(ConfigSurfaceTypes::WINDOW)
The window is default as well.

2022-09-07 22:20 UTC, kchibisov commented on glutin_examples/examples/android.rs
> +                    ContextAttributesBuilder::new().build(Some(raw_window_handle));
You don't need handle here as well. Can pass `None` on build.

2022-09-07 22:49 UTC, kchibisov commented
>I wonder if we can make context current, but without any surface? Make add Api for that or something to help here.

Ah, we can, but it's not guaranteed to work. The issue I was trying to solve is gl functions loading, since I was confused why we need context to be current for that. And it turned out that WGL needs that to perform ICD loading. In general we don't need that if we use `RawWindowHandle` but we do support rendering without passing RawWindowHandle at all. This seems very strange to be fair, and I think that we should force `RawWindowHandle` with WGL.

Though, we can provide a method to get proc address from not current context on supported platforms.

Do you have any idea how to approach the symbol loading here and WGL situation?

2022-09-08 12:23 UTC, MarijnS95 commented
> I'd suggest you to create context out side of `run`. We should advertise the best we can here. The problem is symbol loading, I guess? I wonder if we can make context current, but without any surface? Make add Api for that or something to help here.

It seems you figured out how to clean this up on the glutin API side in #1460 now, I'll rebase and see where we end up.

2022-09-08 12:42 UTC, MarijnS95 commented on glutin_examples/examples/android.rs
> +    // TODO: On Android this is can only be retrieved _AFTER_ Event::Resumed, but
I'll add an option to `create_display()`, and should we provide a "helper" function like this in Glutin? Reason not to do it is leaving the user explicit control over the "display backend" and precedence they use.

2022-09-08 13:14 UTC, kchibisov commented
Now you should be able to reuse your context properly.

2022-09-08 13:32 UTC, MarijnS95 commented
@kchibisov Having a little trouble with that, `make_current()` wants to move the `NotCurrent` context that I create outside of the `run()` loop, but it's not `Copy` nor `Clone` and I can only make it current inside `Resumed` where a `Window` is created.

I can create an `enum` that keeps either the `PossiblyCurrent` or `NotCurrent` context, and then just make it current once we have a `Window`?

2022-09-08 13:41 UTC, MarijnS95 commented
Implemented it that way, by turning `NotCurrentContext` into `PossiblyCurrentContext` when a window is created, and putting it back in `Suspended`. 

This survives the Android lifecycle.

Also tested on desktop by deleting `crate-type = ["cdylib"]`. @kchibisov should we start with a cleanup patch that moves most of the code out of `window.rs` so that we have less duplication between `window.rs` and `android.rs` when I make these changes to it?

2022-09-08 13:47 UTC, kchibisov commented
>Having a little trouble with that, make_current() wants to move the NotCurrent context that I create outside of the run() loop, but it's not Copy nor Clone and I can only make it current inside Resumed where a Window is created.

That's correct, but you can `treat_as_current` if you don't need `NotCurrentContext` thread safety.

>Implemented it that way, by turning NotCurrentContext into PossiblyCurrentContext when a window is created, and putting it back in Suspended.

That's how it should be anyway since you recreate the surface, so you don't have anything current?

>Also tested on desktop by deleting crate-type = ["cdylib"]. @kchibisov should we start with a cleanup patch that moves most of the code out of window.rs so that we have less duplication between window.rs and android.rs when I make these changes to it?

I guess? I don't really mind it that way to be fair since the initialization is a bit different. We can merge it as is.

2022-09-08 13:52 UTC, kchibisov requested changes

2022-09-08 13:52 UTC, kchibisov commented on glutin_wgl_sys/src/lib.rs
> +)]
That seems arbitrary? The old version was intentional here, so revert it.

2022-09-08 14:00 UTC, MarijnS95 commented on README.md
> +Be sure to handle Android's lifecycle correctly when using a `winit` window by only creating a GL surface (currently entire context) after `winit` raises `Event::Resumed`, and destroy it again upon r
@kchibisov This is the thread where we can unify the handling for Android and desktop.

2022-09-08 14:01 UTC, MarijnS95 commented
> I guess? I don't really mind it that way to be fair since the initialization is a bit different. We can merge it as is.

This initialization is supposed to work for desktop as well, because they also receive `Event::Resumed`.

2022-09-08 14:12 UTC, kchibisov commented
>This initialization is supposed to work for desktop as well, because they also receive Event::Resumed.

Yeah, it's just symbol loading won't work on WGL, but we can load it only once on `Resume`? I wonder if we can have just one example at all or it's not possible due to `cdylib` thingy?

2022-09-08 14:22 UTC, MarijnS95 commented
> Yeah, it's just symbol loading won't work on WGL, but we can load it only once on `Resume`?

We might be able to `#[cfg()]` that?

> I wonder if we can have just one example at all or it's not possible due to `cdylib` thingy?

Seems we still need two examples, but we can move 95% of the duplicate code in `{window,android}.rs` to a separate file/module (inside `glutin_examples`).

2022-09-08 14:31 UTC, kchibisov commented
>Seems we still need two examples, but we can move 95% of the duplicate code in {window,android}.rs to a separate file/module (inside glutin_examples).

That sounds good to me.

2022-09-20 21:38 UTC, MarijnS95 commented on glutin_examples/examples/android.rs
> +                let renderer = Renderer::new(&gl_display);
@kchibisov Before attempting to generalize the event loop into a separate file in the `glutin_examples` lib, I tried to make the example run again.

This comment here seems to indicate that `Renderer::new()` only performs symbol loading - which only needs a current-context on WGL - yet it performs a bunch of shader and buffer setup too which require the context to be current on _all_ platforms :grimacing:

2022-09-20 21:47 UTC, kchibisov requested changes
Could you not recreate the renderer on `Resume`? There's no need for that at all and it just slows you down. You also don't need to drop it.

2022-09-20 21:48 UTC, MarijnS95 commented
@kchibisov It'd be nice if you actually read my questions before shooting this down immediately.

2022-09-20 21:53 UTC, kchibisov commented
I mean, I've read it. Nothing stops you from using hand rolled `Lazy`. I can send a patch if you struggle.

2022-09-20 22:09 UTC, MarijnS95 commented
> I mean, I've read it.

Just asking what your design decision was here, and why the selected comment is incomplete.

> Nothing stops you from using hand rolled `Lazy`.

Yawn.

> I can send a patch if you struggle.

Pls halp I can't Rust /s

2022-09-20 22:27 UTC, kchibisov commented on glutin_examples/examples/android.rs
> +                let renderer = Renderer::new(&gl_display);
I think you can remove this comment given it's documented on `get_proc_address`.

2022-09-21 02:21 UTC, kchibisov commented
You may base it on your recently merged PR now.

2022-09-21 09:22 UTC, MarijnS95 commented
@kchibisov Done, can you recheck that this still works on WGL, especially since WGL needs a window _before_ creating a _display_ according to your comments?

2022-09-21 09:24 UTC, MarijnS95 commented on glutin_examples/src/lib.rs
> -    let gl_context = gl_context.make_current(&gl_window.surface).unwrap();
@kchibisov If I understood things correctly `make_current()` now doesn't load any functions anymore, that's done by `Renderer::new()` right? Or does it load a limited set of functions?

2022-09-21 09:24 UTC, MarijnS95 commented on glutin_examples/src/lib.rs
> +    let preference = DisplayApiPreference::WglThenEgl(Some(raw_window_handle.unwrap()));
@kchibisov What if we were to pass `None` here?

2022-09-28 19:12 UTC, kchibisov commented on glutin_examples/src/lib.rs
> +    let preference = DisplayApiPreference::WglThenEgl(Some(raw_window_handle.unwrap()));
This could work, but it won't load any extensions, I'd suggest to not do that on WGL. We might change that in the future, but it's sort of hard to figure out the most ergonomic API for WGL here.

tl;dr right now we must pass the right handle here.

2022-09-28 19:14 UTC, MarijnS95 commented on glutin_examples/src/lib.rs
> +    let preference = DisplayApiPreference::WglThenEgl(Some(raw_window_handle.unwrap()));
In other words: keep the Some + unwrap?

2022-09-28 19:31 UTC, kchibisov commented on glutin_examples/src/lib.rs
> +    let preference = DisplayApiPreference::WglThenEgl(Some(raw_window_handle.unwrap()));
Yeah. Also be aware that we need raw window handle on X11 otherwise you'd need to pass visual from the config to create winit window. Yeah, that's sort of complicated. In general I think it's safer to use visual from config to create winit x11 window...

See `x11_visual` on window builder.

2022-09-28 19:32 UTC, kchibisov commented on glutin_examples/src/lib.rs
> +        unsafe { gl_display.create_context(&config, &context_attributes) }.unwrap_or_else(|_| {
Could we have one `unsafe` for all of them? Nesting like that seems weird.

2022-09-28 19:34 UTC, kchibisov commented on glutin_wgl_sys/src/lib.rs
> +#![cfg(target_os = "windows")]
You could just `#![cfg(windows)]` here.

2022-09-29 16:04 UTC, MarijnS95 commented on glutin_wgl_sys/src/lib.rs
> +#![cfg(target_os = "windows")]
Sure, I'll do that for all `target_os = "windows"` across the repo for consistency.

2022-09-29 16:15 UTC, MarijnS95 commented on glutin_examples/src/lib.rs
> +    let preference = DisplayApiPreference::WglThenEgl(Some(raw_window_handle.unwrap()));
@kchibisov Not sure I follow. Searching for `x11_visual` shows references inside GLX's `find_configs()`; in other words you want me to make sure on X11 the window is created before we call `config_template()`, but it's fine to not have it before display creation, for this:

https://github.com/rust-windowing/glutin/blob/ec74687ed2acede620a3cb0d54f85db877725f3c/glutin/src/api/glx/config.rs#L99-L103

Also noticed a little bug that `::Resumed` would open another window on these platforms, even if we already created one (but the first one seems to be invisible on X11).

2022-10-04 06:27 UTC, kchibisov commented on glutin_examples/src/lib.rs
> +    let preference = DisplayApiPreference::WglThenEgl(Some(raw_window_handle.unwrap()));
I'd handle that myself then. I meant the winit API here, sorry for not being clear.

2022-10-04 07:19 UTC, kchibisov approved these changes
This should be good to go once CI passes. I've updated the handling of X11 to be more robust given that it was proven that it's not really working.

Not sure if I want to update internal handling of X11 config picking, but might alter it to not consider raw-window-handle at all.

2022-10-04 07:44 UTC, merged

2022-10-04 07:44 UTC, kchibisov commented
Thanks.

2022-10-04 07:45 UTC, MarijnS95 commented
@kchibisov Thank _you_ for patching up the X11 situation and getting this in!