Switch from `lazy_static` to `once_cell`
rust-windowing/glutin pull request #1432
Opened 2022-07-29 13:31 UTC by a1phyr

`winit` has just done it, so `glutin` should probably do the same.

- [ ] Tested on all platforms changed
- [x] Compilation warnings were addressed
- [x] `cargo fmt` has been run on this branch
- [x] `cargo doc` builds successfully
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

2022-07-29 17:06 UTC, kchibisov requested changes

2022-07-29 17:06 UTC, kchibisov commented on glutin/Cargo.toml
> +once_cell = "1.10"
Could you specify the current latest version instead?

2022-07-29 20:19 UTC, MarijnS95 approved these changes
Other than the versioning issue (I'd personally write `"1"`), this seems fine to me. I thought we already did this conversion in Glutin or I forgot to submit it :sweat_smile:

2022-07-30 16:39 UTC, kchibisov approved these changes

2022-07-30 16:40 UTC, merged