WIP: Add EGLDevice wrappers
rust-windowing/glutin pull request #1484
Opened 2022-10-12 03:00 UTC by i509VCB

Not completely done yet, but it is functional.

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [X] Created or updated an example program if it would help users understand this functionality

2022-10-28 12:07 UTC, kchibisov requested changes
This looks mostly good, I'd say.

Left some minor notes, also, don't need to store `png` files in the repository given that you generate them, so please, delete it.

2022-10-28 12:07 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +        Device::from_ptr(device)
Can merge and have branching instead of return like that.

2022-10-28 12:07 UTC, kchibisov commented on glutin_examples/Cargo.toml
> +png = "0.17.6"
That's optional based on `egl` feature.

2022-10-28 12:07 UTC, kchibisov commented on glutin_examples/examples/egl_device/main.rs
> +        .join("output.png");
Could you log to `stdout` that you wrote image to path?

2022-10-28 20:14 UTC, i509VCB commented on glutin/src/api/egl/device.rs
> +    // TODO: Device extensions
It's not clear how we want to expose extensions in EGL at the moment. Or should this just be exposed.

2022-10-28 20:27 UTC, kchibisov commented on glutin/src/api/egl/device.rs
> +    // TODO: Device extensions
You mean device extensions? We do have display ones for example, you can simply provide a reference to a `HashSet`?

2022-10-28 20:37 UTC, i509VCB commented on glutin/src/api/egl/display.rs
> +    #[allow(clippy::vec_init_then_push)]
Nope, doesn't solve it.

2022-10-28 20:49 UTC, i509VCB commented on glutin/src/api/egl/display.rs
> +        }
EGLDevice won't work in `DisplayL::get_platform_display` or `Display::get_platform_display_ext` because it is not a valid RawWindowHandle api.

2022-10-29 00:28 UTC, kchibisov requested changes

2022-10-29 00:28 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +    fn initialize_display(display: EGLDisplay) -> Result<Self> {
you can pass EGL as argument here?

2022-10-29 00:28 UTC, kchibisov commented on glutin/src/api/egl/device.rs
> +        let egl = super::EGL.as_ref().unwrap();
From what I see you can pass EGL as arguments as well?

2022-10-29 00:28 UTC, kchibisov commented on glutin_examples/examples/egl_device.rs
> +#[cfg(feature = "egl")]
```suggestion
#[cfg(egl_backend)]
```

2022-10-29 00:28 UTC, kchibisov commented on glutin_examples/examples/egl_device.rs
> +    #[cfg(feature = "egl")]
```suggestion
    #[cfg(egl_backend)]
```

2022-10-29 01:03 UTC, kchibisov commented on glutin_examples/examples/egl_device.rs
> +        println!("Picked a config with {} samples", config.num_samples());
If you don't try to pick with higher samples then I don't think it's required, but would be nice to pick more samples so we have smooth triangle.

2022-11-12 05:31 UTC, kchibisov approved these changes

2022-11-12 05:31 UTC, merged

2022-11-12 05:32 UTC, kchibisov commented
Thanks.