Add glutin-winit GlWindow trait helper
rust-windowing/glutin pull request #1545
Opened 2022-12-20 12:37 UTC by alexheretic

I thought I'd experiment with reducing the noise using glutin-winit vs glutin `0.29`. This pr adds `glutin_winit::GlWindow` trait with extensions for winit `Window`s. (It could alternatively be called `glutin_winit::WindowExt` if you prefer).

I updated the example replacing the example `GlWindow` struct as it's simpler to use the trait.

I think this is quite a light touch, but still useful. Wdyt?

- [x] ~Tested on all platforms changed~
- [x] ~Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users~
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] Created or updated an example program if it would help users understand this functionality

2022-12-20 12:49 UTC, alexheretic commented on glutin_examples/src/lib.rs
>                                  NonZeroU32::new(size.height).unwrap(),
I left the resize usage plain here as it was before, though `GlWindow::resize_surface` could be used.

Note: In my game & examples I don't process resizes (which also involves more than just surface resizing) like this for each `WindowEvent::Resized` as (iirc) the events can outpace the resize operations. I found it better to process resizes after all events so multiple queue resizes would result in a single resize. For this case `GlWindow::resize_surface` de-clutters the most.

2022-12-24 11:23 UTC, kchibisov commented
Yes could you create a separate CHANGELOG in the glutin-winit crate?

2022-12-24 11:31 UTC, kchibisov requested changes

2022-12-24 11:31 UTC, kchibisov commented on glutin-winit/src/window.rs
> +    fn resize_surface(&self, surface: &Surface<WindowSurface>, context: &PossiblyCurrentContext);
Could we accept `&impl Traits` here instead? So it'll be more flexible.

2022-12-24 11:31 UTC, kchibisov commented on glutin-winit/src/window.rs
> +    /// Converts to non-zero `(width, height)`.
The trait is unused. Speaking aside it's fine to add such helper to winit types directly.

2023-01-05 14:42 UTC, alexheretic commented on glutin-winit/src/window.rs
> +    /// Converts to non-zero `(width, height)`.
It is used, but could be make non-public. It just seemed useful to have working with winit physical sizes and glutin API.

2023-01-10 08:46 UTC, kchibisov requested changes

2023-01-10 08:46 UTC, kchibisov commented on glutin-winit/src/window.rs
> +    /// Converts to non-zero `(width, height)`.
You may want to submit that into winit instead? Like as I said, I don't see any issue with such thing, I just think that it may benefit winit directly, since you want to check that both of your sizes are not zero. So I'd suggest to move it there instead.

2023-01-10 08:46 UTC, kchibisov commented on glutin-winit/CHANGELOG.md
> +- Fix WGL window initialization.
Add a new line.

2023-01-10 08:46 UTC, kchibisov commented on glutin-winit/CHANGELOG.md
> +# Version 0.2.0
ditto.

2023-01-10 08:46 UTC, kchibisov commented on glutin-winit/CHANGELOG.md
> +# Version 0.1.0
ditto.

2023-01-10 08:46 UTC, kchibisov commented on glutin-winit/CHANGELOG.md
> +- Add traits `GlWindow`, `NonZeroU32PhysicalSize` with helper methods for building and resizing surfaces
```suggestion
# Unreleased

- Add traits `GlWindow`, `NonZeroU32PhysicalSize` with helper methods for building and resizing surfaces
```

2023-01-10 08:46 UTC, kchibisov commented on glutin-winit/CHANGELOG.md
> +- Add traits `GlWindow`, `NonZeroU32PhysicalSize` with helper methods for building and resizing surfaces
Without the part about `NonZeroU32PhysicalSize`.

2023-01-10 10:22 UTC, alexheretic commented on glutin-winit/src/window.rs
> +    /// Converts to non-zero `(width, height)`.
I'd rather make this private than block the pr on winit releases tbh

2023-01-10 10:28 UTC, alexheretic commented on glutin-winit/CHANGELOG.md
> +- Fix WGL window initialization.
I think it makes sense to use a explicit suggestion for this kind of edit, easy for you to write and me to apply. You can also just do such edits directly.

2023-01-10 10:31 UTC, kchibisov commented
I mean that making it private doesn't make any sense, since it's not used internally anyway? I'd rather remove for now and bring back if necessary.

2023-01-10 10:37 UTC, alexheretic commented
> I mean that making it private doesn't make any sense, since it's not used internally anyway? I'd rather remove for now and bring back if necessary.

But it is used, in both `GlWindow::build_surface_attributes` & `GlWindow::resize_surface`.

2023-01-16 18:09 UTC, kchibisov approved these changes

2023-01-16 23:35 UTC, merged

2023-01-17 10:09 UTC, alexheretic commented
Thanks for reviewing @kchibisov !

2023-01-26 11:05 UTC, alexheretic commented
@kchibisov any chance of a new release of _glutin-winit_? I'd like to make use of these features.

2023-01-26 11:24 UTC, kchibisov commented
I was going to bump along the winit bump, but I guess I can patch bump glutin-winit. Will do that later today.

2023-01-27 02:01 UTC, kchibisov commented
Released `v0.2.2`.

Next time you could open an issue if you need either glutin or glutin-winit released, since most bumps to them will likely be non-breaking.