glutin-winit: Update to winit 0.28
rust-windowing/glutin pull request #1560
Opened 2023-02-02 09:10 UTC by alexheretic

Also fix the rust 1.67 clippy lints (since these are deny).

@kchibisov can this be released as _glutin-winit_ `0.3`?

- [x] Tested on all platforms changed _(assuming winit itself was tested)_
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- ~[x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior~
- ~[x] Created or updated an example program if it would help users understand this functionality~

2023-02-02 11:57 UTC, kchibisov commented
Seems like you should add the responsible winit features for android, like game/native activity as well. Could you also point to winit 0.28.1 explicitly.

>@kchibisov can this be released as glutin-winit 0.3?

Sure.

2023-02-02 12:01 UTC, kchibisov requested changes

2023-02-02 12:01 UTC, kchibisov commented on glutin_examples/Cargo.toml
>  glutin = { path = "../glutin", default-features = false }
I think you can also disable `winit/wayland-csd-adwaita-notitle` since winit is using `ab_glyph` now by default.

2023-02-02 15:50 UTC, MarijnS95 approved these changes
Not tested but this looks sensible.

2023-02-02 15:50 UTC, MarijnS95 commented on glutin_examples/examples/android.rs
> +fn android_main(app: winit::platform::android::activity::AndroidApp) {
Nit: I'd import `AndroidApp` just like the trait is imported, instead of fully qualifying it.

2023-02-02 16:10 UTC, alexheretic commented
> Not tested but this looks sensible.

Tbf android isn't really a platform I can help support. I just followed the migration recommendations from the winit repo to make it look correct & compile.

2023-02-03 18:47 UTC, kchibisov approved these changes

2023-02-03 18:47 UTC, merged