egl/surface: Don't dereference native window pointer before passing to legacy `CreateWindowSurface`
rust-windowing/glutin pull request #1585
Opened 2023-04-01 14:51 UTC by MarijnS95

Fixes #1584

Just like for KHR and EXT the native window _is_ `egl::NativeWindowType` (which is a `*const c_void` under the hood).  By casting it to _a pointer of_ `egl::NativeWindowType` instead, and derferencing that, we'd be reading the first few bytes of whatever this opaque handle was pointing to (if it even is a valid pointer) and segfaulting on at least Android inside `libEGL`.  In other words, never dereference opaque handles which may not even be a valid memory address in the first place.

- [ ] Tested on all platforms changed
    - [x] Android
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

2023-04-01 15:01 UTC, kchibisov commented
This is actually wrong, because the function accepts `NativeWindowType`. If you look into the code we have the value is behind double pointer and then we deref it so we pass the `* void`.

For example on X11 the default type passed to the client is `ulong`, so we dereference it and pass the `ulong`.

See https://github.com/rust-windowing/glutin/issues/1566 . It was a bug before due to me blindly following the KHR extension, however the dereference should be present.

Maybe some logic is not really sane here... Would suggest to consult the EGL spec wrt android here...

2023-04-01 15:01 UTC, MarijnS95 commented
> `egl::NativeWindowType` (which is a `*const c_void` under the hood).

Ouch, on Windows it's `isize`, probably because of being `HWND`:

https://github.com/rust-windowing/glutin/actions/runs/4583750441/jobs/8094795641#step:7:72

@kchibisov perhaps all backends should use `EGLNativeWindowType`, as it should not always be interpreted as a void pointer?

2023-04-01 15:02 UTC, MarijnS95 commented
> If you look into the code we have the value is behind double pointer

`NativeWindow::as_ptr()` is not?

2023-04-01 15:03 UTC, kchibisov commented
On the other hand the KHR function accepts the `*NativeWindowTYpe`, so it must be a double pointer on Android/Wayland, and a single pointer on X11.

So if you look into both functions the signatures are different.

https://registry.khronos.org/EGL/sdk/docs/man/html/eglCreateWindowSurface.xhtml
https://registry.khronos.org/EGL/sdk/docs/man/html/eglCreatePlatformWindowSurface.xhtml

2023-04-01 15:04 UTC, MarijnS95 commented
Oh I see what stupidity #1570 is doing. `as_ptr()` takes `&self` and you cast the auto-borrowed `window_id` to a raw pointer, whereas on wayland/windows/android/gbm this auto-borrow is first dereferenced :facepalm:

2023-04-01 15:08 UTC, kchibisov commented
>Oh I see what stupidity #1570 is doing. as_ptr() takes &self and you cast the auto-borrowed window_id to a raw pointer, whereas on wayland/windows/android/gbm this auto-borrow is first dereferenced facepalm

So it seems like I was also insane when I wrote this, because it's always a single pointer in the end. It just some non pointer types are moving to pointer types. I'd suggest to rewrite it in a more sane way...

2023-04-01 15:09 UTC, MarijnS95 commented
> So it seems like I was also insane when I wrote this, because it's always a single pointer in the end. It just some non pointer types are moving to pointer types(which they clearly should). I'd suggest to rewrite it in a more sane way...

Yeah I think the fix shown there wouldn't have worked on Xlib/Xcb + the KHR/EXT extension (if that's even possible) because we'd be passing a pointer to `window_id` :)

2023-04-01 15:14 UTC, MarijnS95 commented
@kchibisov so there are a few questions to answer, because we can write this "sanely" in a few different ways:

1. Always define `EGLNativeWindowType` to be `*mut c_void`;
2. Keep `EGLNativeWindowType` platform-specific, but more rigorously `cfg()` the entries in `NativeWindow` (so that we don't have to cast a `HWND` when not compiling for Windows, that match arm won't be reached anyway);

2023-04-01 15:16 UTC, MarijnS95 commented
> So if you look into both functions the signatures are different.
> 
> https://registry.khronos.org/EGL/sdk/docs/man/html/eglCreateWindowSurface.xhtml https://registry.khronos.org/EGL/sdk/docs/man/html/eglCreatePlatformWindowSurface.xhtml

Not sure if you noticed already, but both functions are identical afaik. One takes `NativeWindowType` (typedef'd to `void *`) and the other takes `void *` directly without a typedef.

2023-04-01 15:17 UTC, MarijnS95 commented
> No, way you did won't work on X11, because you need actually what it was doing before with pointers. Because the native window type was not the pointer in the first place actually.

Oh that's very unfortunate... Yikes. Then the original push was good afaik, after fixing casting issues on Windows?

2023-04-01 15:17 UTC, kchibisov commented
On X11 `NativeWindowType` is a XID though? I remember when I've passed it directly it wasn't working and if you look at what I pass now it's a `& NativeWindowType` on X11, because I don't deference.

2023-04-01 15:18 UTC, kchibisov commented
I can submit a patch to fix this issue if you don't mind.

2023-04-01 15:30 UTC, MarijnS95 commented
> I can submit a patch to fix this issue if you don't mind.

No need for that, I've reverted the change and now made the output of `as_ptr()` consistent across the platforms.

That is, on Windows `EGLNativeWindowType = HWND = *const c_void`.

2023-04-01 15:36 UTC, kchibisov commented
Hm, but the thing is that the NativeWindow is different.

You could try something like that.

```diff
diff --git a/glutin/src/api/egl/surface.rs b/glutin/src/api/egl/surface.rs
index fc396c2..a585732 100644
--- a/glutin/src/api/egl/surface.rs
+++ b/glutin/src/api/egl/surface.rs
@@ -102,7 +102,7 @@ impl Display {
                 self.inner.egl.CreatePlatformPixmapSurface(
                     display,
                     *config.inner.raw,
-                    native_pixmap.as_ptr(),
+                    native_pixmap.as_platfrom_pixmap(),
                     attrs.as_ptr(),
                 )
             },
@@ -111,7 +111,7 @@ impl Display {
                 self.inner.egl.CreatePlatformPixmapSurfaceEXT(
                     display,
                     *config.inner.raw,
-                    native_pixmap.as_ptr(),
+                    native_pixmap.as_platfrom_pixmap(),
                     attrs.as_ptr(),
                 )
             },
@@ -121,7 +121,7 @@ impl Display {
                 self.inner.egl.CreatePixmapSurface(
                     display,
                     *config.inner.raw,
-                    *(native_pixmap.as_ptr() as *const egl::NativePixmapType),
+                    native_pixmap.as_native_pixmap(),
                     attrs.as_ptr(),
                 )
             },
@@ -180,7 +180,7 @@ impl Display {
                 self.inner.egl.CreatePlatformWindowSurface(
                     display,
                     *config.inner.raw,
-                    native_window.as_ptr().cast(),
+                    native_window.as_platform_window(),
                     attrs.as_ptr(),
                 )
             },
@@ -189,7 +189,7 @@ impl Display {
                 self.inner.egl.CreatePlatformWindowSurfaceEXT(
                     display,
                     *config.inner.raw,
-                    native_window.as_ptr().cast(),
+                    native_window.as_platform_window(),
                     attrs.as_ptr(),
                 )
             },
@@ -199,7 +199,7 @@ impl Display {
                 self.inner.egl.CreateWindowSurface(
                     display,
                     *config.inner.raw,
-                    *(native_window.as_ptr() as *const egl::NativeWindowType),
+                    native_window.as_native_window(),
                     attrs.as_ptr(),
                 )
             },
@@ -496,7 +496,27 @@ impl NativeWindow {
         }
     }
 
-    fn as_ptr(&self) -> *mut ffi::c_void {
+    fn as_native_window(&self) -> egl::NativeWindowType {
+        match *self {
+            #[cfg(wayland_platform)]
+            Self::Wayland(wl_egl_surface) => wl_egl_surface,
+            #[cfg(x11_platform)]
+            Self::Xlib(window_id) => window_id as egl::NativeWindowType,
+            #[cfg(x11_platform)]
+            Self::Xcb(window_id) => window_id as egl::NativeWindowType,
+            Self::Win32(hwnd) => hwnd as egl::NativeWindowType,
+            Self::Android(a_native_window) => a_native_window,
+            Self::Gbm(gbm_surface) => gbm_surface,
+        }
+    }
+
+    // NOTE: on X11 and Windows the native window are XID and HWND
+    // respectively, however the platform window should be behind a
+    // pointer. The function accepts the `&self`, so it automatically
+    // borrows the value and then we simply cast the pointer. On other
+    // platforms though, the default window handle is a pointer already,
+    // so we simply derefence the just taken borrow.
+    fn as_platform_window(&self) -> *mut ffi::c_void {
         match self {
             #[cfg(wayland_platform)]
             Self::Wayland(wl_egl_surface) => *wl_egl_surface,
@@ -523,7 +543,17 @@ impl Drop for NativeWindow {
 }
 
 impl NativePixmap {
-    fn as_ptr(&self) -> *mut ffi::c_void {
+    fn as_native_pixmap(&self) -> egl::NativePixmapType {
+        match *self {
+            Self::XlibPixmap(xid) => xid as egl::NativePixmapType,
+            Self::XcbPixmap(xid) => xid as egl::NativePixmapType,
+            Self::WindowsPixmap(hbitmap) => hbitmap as egl::NativePixmapType,
+        }
+    }
+
+    // NOTE: see the `NativeWindow::as_platform_window`. The same applies to this
+    // function.
+    fn as_platfrom_pixmap(&self) -> *mut ffi::c_void {
         match self {
             Self::XlibPixmap(xid) => xid as *const _ as *mut _,
             Self::XcbPixmap(xid) => xid as *const _ as *mut _,

```

2023-04-01 15:51 UTC, MarijnS95 commented
@kchibisov Oh right, we should solve the same dereference for pixmaps then, since `as_ptr` now returns a pointer to `xid` or _a pointer to `HBITMAP`_, and derferences it for legacy display only.

In other words, that code would then only work for Xlib/Xcb on KHR/EXT, and only for legacy on Windows?

---

To make your patch work we'd have to also `cfg(windows)` the `Win32` arm, because it has to cast to `HWND = isize`, as pointed out by an earlier CI failure. Is that okay by you or do you rather keep the current approach?

2023-04-01 15:57 UTC, MarijnS95 commented
Oh, reading back up on https://github.com/rust-windowing/glutin/issues/1566#issuecomment-1424652584, it seems that there _is_ a syntactical difference between the pointer and XID, specifically in the legacy `eglCreateWindowSurface`, but only on X for `window_id`/`XID`?

Did I grasp this correctly? Substitute for pixmap where appropriate:

||`eglCreateWindowSurface`|`eglCreatePlatformWindowSurfaceKHR`|`eglCreatePlatformWindowSurfaceEXT`|
|-|-|-|-|
|Windows|`HWND`|`HWND`|`HWND`|
|X|`XID`|`*XID`|`*XID`|
|Android|`void *`|`void *`|`void *`|

2023-04-01 16:02 UTC, kchibisov commented
Shouldn't it be `HWND *` for windows with `eglCreatePlatformWindowSurfaceKHR` and `HWND` with normal window? I don't have EGL on windows, so can't test for segfault :p

2023-04-01 16:03 UTC, MarijnS95 commented
> Shouldn't it be `HWND *` for windows with `eglCreatePlatformWindowSurfaceKHR` and `HWND` with normal window? I don't have EGL on windows, so can't test for segfault :p

I'd have to reboot to Windows to test out this theory, but it's currently returning `HWND` (see the dereference in `master`) but for `HBITMAP` it returns a pointer to it :)

On that note, the public API takes `isize` for `HBITMAP` but `*mut c_void` for `HWND`...

2023-04-01 16:06 UTC, kchibisov commented
I think HWND was always an `*mut c_void` with the WinAPI crate, then when we've migrated to `windows-sys` it became `isize` instead, so in my understanding it was the same as with `XID`.

In general, both `HWND` and `HBITMAP` should be the same definition from what I understand, but I have no clue how to test what windows really wants from me here. For X11 I simply read the mesa code :/

2023-04-01 16:25 UTC, MarijnS95 commented
@kchibisov Hmm right, no I think despite the `isize` in `windows-sys` it should still be passed as-is, but let's test.

For now this change is spiraling out of control into a rabbit-hole of changes. What should we tackle first, and the rest in what order? I can reboot to windows and test all three functions (assuming the extensions are available), and cook up a pixmap example to do the same.

Then, for Android as #1584 pointed out it must be the `ANativeWindow` pointer in all three cases, no changes. For wayland this should be the same.

Then if you can test that XID/window_id must only be a pointer on KHR/EXT I think we're good.

Finally, we have the type changes. I can use `egl::NativeWindow` but it must return a `*const c_void` as `&self` is not borrowed mutable - unless we want to do a const-cast. Then for windows, should we change the public `NativeWindow` to `isize` to match `NativePixmap` and `windows-sys`? We could even reuse the types from `windows-sys` which are currenltly only used in the WGL code... and `egl_sys` :)

2023-04-01 16:31 UTC, kchibisov commented
I've verified X11 with my patch(and everything works fine). So only the `EGL` part of windows was never tested, because simply my driver doesn't provide the `EGL` libraries. Be aware that you might end up with the same situation.

To test this on Windows you'll need to

1. Change the `glutin-winit` to prefer `EGL` and ensure that you're using EGL on Windows(my hardware can't do that, so I can't test).
2. Simply use the current patch semantics wrt what is pointer and what is not. From my understanding you should pass `&HWND` for `Platform` and `HWND` for native.

If any of that crashes adjust the semantics to not do so(maybe you'll need passing the thing as is). From my understanding though, the `HWND` is not a real pointer, given that it has arbitrary data encoded into it.

>We could even reuse the types from windows-sys which are currenltly only used in the WGL code... and egl_sys :)

We probably could, but it's a one more deps and a breaking change I'm not into for now...

2023-04-01 16:35 UTC, MarijnS95 commented
> I've verified X11 with my patch(and everything works fine). So only the `EGL` part of windows was never tested, because simply my driver doesn't provide the `EGL` libraries. Be aware that you might end up with the same situation.

Okay, I'll apply your patch on top to make sure X11 starts working again. Did you test all of `Legacy`/`KHR`/`EXT` (by changing the logic in `Display::new`)?

> From my understanding though, the `HWND` is not a real pointer, given that it has arbitrary data encoded into it.

Heh, and so we're back at the original "don't dereference whatever comes out of `fn as_ptr()`".
 
> > We could even reuse the types from windows-sys which are currently only used in the WGL code... and egl_sys :)
> 
> We probably could, but it's a one more deps and a breaking change I'm not into for now...

Even without the dep, changing from `*mut c_void` to `isize` would also be breaking.

2023-04-01 16:43 UTC, MarijnS95 commented on glutin_egl_sys/src/lib.rs
>  pub type EGLNativeWindowType = *const raw::c_void;
We can probably revert this now, and simplify for `cfg(windows)` and `cfg(not(windows))`. Then, do the same for `EGLNativePixmapType` on `HBITMAP`?

2023-04-01 17:40 UTC, kchibisov commented on glutin_egl_sys/src/lib.rs
>  pub type EGLNativeWindowType = *const raw::c_void;
I'd suggest to keep the crate types as they were before, at least unless we figure out the semantics.

2023-04-01 17:41 UTC, kchibisov commented
>Okay, I'll apply your patch on top to make sure X11 starts working again. Did you test all of Legacy/KHR/EXT (by changing the logic in Display::new)?

Yes, that's what I do. You can simply `Ok(::new.unwrap())` to ensure that you're using the right thing.

2023-04-01 20:39 UTC, MarijnS95 commented on glutin/src/api/egl/surface.rs
> +    #[cfg(android)]
> `operating system used in target family position`

Looks like the `android` CFG alias isn't working.

2023-04-01 20:42 UTC, MarijnS95 commented on glutin_egl_sys/src/lib.rs
>  pub type EGLNativeWindowType = *const raw::c_void;
Done, but as said that causes `as_native_window` to return an `isize` (typedef for `egl::NativeWindowType`) on Windows and `*mut c_void` everywhere else so I had to `cfg`-guard all other `NativeWindow` arms.

2023-04-01 20:43 UTC, MarijnS95 commented
Unfortunately my Windows system doesn't have `libEGL.so` (AMD RX6800 XT) and I don't know of a sensible way to acquire it.

Regarding Mesa, perhaps we could peek through the EGL-over-WGL backend: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/12727?commit_id=3415bf0268884bf3c16d495a4e1afd30d67bc71d? Not sure if the native window type for EGL is still a `HWND` or something opaque Linux'y within WSL.

2023-04-01 20:49 UTC, kchibisov commented
>Regarding Mesa, perhaps we could peek through the EGL-over-WGL backend: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/12727?commit_id=3415bf0268884bf3c16d495a4e1afd30d67bc71d? Not sure if the native window type for EGL is still a HWND or something opaque Linux'y within WSL.

I've read through glfw code, and it's passed as is. Only on X11 you have the pointer trick thing I was doing.

2023-04-01 20:50 UTC, kchibisov commented on glutin_egl_sys/src/lib.rs
>  pub type EGLNativeWindowType = *const raw::c_void;
Let's define it as pointer then, the crate is intended for glutin use only.

2023-04-01 20:51 UTC, kchibisov commented on glutin/src/api/egl/surface.rs
> +    #[cfg(android)]
While we're at it, I'd suggest to change the names, like `android_platform`.  Or similar to what we have in https://github.com/rust-windowing/winit/blob/fbea75d31f4025825e9bf88b99d7c92e4eb79273/build.rs#L35 given that winit has it right.

2023-04-01 21:45 UTC, kchibisov requested changes

2023-04-01 21:45 UTC, kchibisov commented on glutin-winit/build.rs
>          wasm: { target_arch = "wasm32" },
Use `android_platform` instead of just `android`, then it'll work. Same rename change should be done to the `macos`,`ios`, and `wasm`.

2023-04-01 21:45 UTC, kchibisov commented on glutin/src/surface.rs
> +    // next breaking release. Either both are `*mut c_void`, or `isize`.
I picked isize, because `hwnd`(inside the windows-sys) is `isize`. And given that we're using `isize` there's no inconsistency.

2023-04-01 21:45 UTC, kchibisov commented on glutin/src/api/egl/surface.rs
> +    #[cfg(unix)]
that's `free_unix`, macOS doesn't have gbm.

2023-04-02 18:59 UTC, MarijnS95 commented on glutin/src/surface.rs
> +    // next breaking release. Either both are `*mut c_void`, or `isize`.
Then I'll move this comment to `NativeWindow::Win32`, which uses `*mut c_void` while `windows-sys` says it should be an `isize`.

2023-04-02 19:09 UTC, MarijnS95 commented on glutin-winit/build.rs
>          wasm: { target_arch = "wasm32" },
Yeah, you said that yesterday in https://github.com/rust-windowing/glutin/pull/1585#discussion_r1155173734.

2023-04-02 19:12 UTC, MarijnS95 commented on glutin/src/surface.rs
> +    // next breaking release. Either both are `*mut c_void`, or `isize`.
In fact `NativeWindow` is private to `egl` so I've updated the type instead.

2023-04-02 19:17 UTC, MarijnS95 commented on glutin/src/api/egl/surface.rs
> +    #[cfg(android)]
@kchibisov fwiw `winit` defines `wasm_platform` but the macros below use `not(wasm)` instead of `not(wasm_platform)`. Is there an undocumented `wasm` for this `target_family` [just like there's `unix` and `windows`](https://doc.rust-lang.org/reference/conditional-compilation.html#unix-and-windows)?

2023-04-02 19:18 UTC, MarijnS95 commented on glutin/src/api/egl/surface.rs
> +            Self::WindowsPixmap(hbitmap) => hbitmap as egl::NativePixmapType,
@kchibisov fwiw we can skip this cast if we similarly `#[cfg(windows)]` `WindowsPixmap`, because both `egl::NativePixmapType` and `HBITMAP` are `isize` there. Should I?

2023-04-02 19:21 UTC, MarijnS95 commented on glutin/src/api/egl/surface.rs
> +            Self::WindowsPixmap(hbitmap) => hbitmap as egl::NativePixmapType,
Ah nevermind again, I keep mixing things up as `NativeWindow` (re-wrapper for `RawWindowHandle`) is private to `egl` but `NativePixmap` is global and public outside of `egl`.

2023-04-02 20:27 UTC, kchibisov requested changes
Will also need a `CHANGELOG` entry for that.

2023-04-02 20:27 UTC, kchibisov commented on glutin/src/api/egl/surface.rs
> +    /// Returns the underlying handle value
```suggestion
    /// Returns the underlying handle value.
```

2023-04-02 20:27 UTC, kchibisov commented on glutin/src/api/egl/surface.rs
> +    /// The returned pointer is a cast of the `&self` borrow.
```suggestion
    /// # Safety:
    ///
    /// On X11 the returned pointer is a cast of the `&self` borrow.
```

2023-04-02 20:27 UTC, kchibisov commented on glutin/src/api/egl/surface.rs
> +    /// the raw underlying handle value on all other platforms.
```suggestion
    /// Returns a pointer to the underlying handle value on X11,
    /// the raw underlying handle value on all other platforms.
```

2023-04-02 20:27 UTC, kchibisov commented on glutin/src/api/egl/surface.rs
> +    /// Returns the underlying handle value
```suggestion
    /// Returns the underlying handle value.
```

2023-04-02 20:27 UTC, kchibisov commented on glutin/src/api/egl/surface.rs
> +    /// the raw underlying handle value on all other platforms.
```suggestion
    /// Returns a pointer to the underlying handle value on X11,
    /// the raw underlying handle value on all other platforms.
```

2023-04-02 20:27 UTC, kchibisov commented on glutin/src/api/egl/surface.rs
> +    /// The returned pointer is a cast of the `&self` borrow.
```suggestion
    /// # Safety:
    ///
    /// On X11 the returned pointer is a cast of the `&self` borrow.
```

2023-04-02 21:08 UTC, kchibisov approved these changes

2023-04-02 22:07 UTC, merged