egl: change surface to be `Send`
rust-windowing/glutin pull request #1662
Opened 2023-12-27 23:58 UTC by vially

- [ ] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

2023-12-28 18:53 UTC, kchibisov requested changes
I'll look into example latter.

2023-12-28 18:53 UTC, kchibisov commented on CHANGELOG.md
> +- **Breaking:** Change `Surface` to be `Send`. This makes it consistent with the context, so now they are both `Send` but not `Sync`.
it's not a breaking change, just say that it's now `Send`.

2023-12-28 19:52 UTC, vially commented on CHANGELOG.md
> +- **Breaking:** Change `Surface` to be `Send`. This makes it consistent with the context, so now they are both `Send` but not `Sync`.
Fixed in https://github.com/rust-windowing/glutin/pull/1662/commits/5641543019c39a9a403bafd0198681f77b57264c.

2024-02-12 18:08 UTC, kchibisov commented
macOS tested.
X11 tested.

2024-02-12 18:13 UTC, kchibisov commented
Windows tested.

2024-02-12 18:13 UTC, kchibisov approved these changes

2024-02-12 18:13 UTC, merged

2024-02-12 18:36 UTC, kchibisov commented
Pushed 0.31.3 with that, let's see how it survives.