Update `raw-window-handle` to v0.6
rust-windowing/glutin pull request #1670
Opened 2024-03-13 02:21 UTC by declantsien

- [ ] Tested on all platforms changed
Only tested on devices using Linux
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
 None
- [x] Created or updated an example program if it would help users understand this functionality

2024-03-18 18:58 UTC, kchibisov commented
We already have #1582 for that, though we have an option for `0.6` just for the time being unless I have time to look into the safe handle stuff and how it could be approached in glutin.

2024-03-18 19:11 UTC, kchibisov requested changes

2024-03-18 19:11 UTC, kchibisov commented on glutin/src/api/egl/config.rs
> +                        if xcb.visual_id.is_some() && xcb.visual_id.unwrap().get() > 0 =>
Do not unwrap here, just make it default to zero and follow the old logic.

2024-03-18 19:11 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +                (egl::PLATFORM_X11_KHR, handle.display.unwrap().as_ptr())
Do not unwrap here. IIRC passing `null` is fine and it'll just open a default display or error, we shouldn't crash.

2024-03-18 19:11 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +                (egl::PLATFORM_X11_EXT, handle.display.unwrap().as_ptr())
Same about `unwrap`.

2024-03-18 19:11 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +                (egl::PLATFORM_XCB_EXT, handle.connection.unwrap().as_ptr())
I don't remember the semantics here, but I think `null` is also fine here. In general I'd suggest to test.

2024-03-18 19:11 UTC, kchibisov commented on glutin/src/api/glx/display.rs
> +                (GlxDisplay(handle.display.unwrap().as_ptr() as *mut _), handle.screen as i32)
refactor it `if let else`

2024-03-18 19:11 UTC, kchibisov commented on glutin/src/api/wgl/display.rs
> +                        window.hinstance.unwrap().get() as _,
I don't remember the semantics when `0` is passed. Would suggest to check, probably it's also _fine_

2024-03-18 19:11 UTC, kchibisov commented on CHANGELOG.md
> +- Updated raw-window-handle dependency to 0.6. See [raw-window-handle CHANGELOG](https://github.com/rust-windowing/raw-window-handle/blob/v0.6.0/CHANGELOG.md#060-2023-09-30) for more info.
```suggestion

- **Breaking:** updated raw-window-handle dependency to 0.6.
```

2024-03-18 19:11 UTC, kchibisov commented on glutin-winit/src/window.rs
> +            Err(err) => panic!("Error {err:?}"),
We shouldn't panic here, probably it's better to propagate.

2024-03-18 19:12 UTC, kchibisov commented
I'd just post a review, since there's nothing wrong with just using `raw` version of 0.6, since it's just small update.

2024-03-18 19:19 UTC, MarijnS95 commented
A lot of changes here may snoop the implementation from https://github.com/ash-rs/ash/pull/799 which - to my knowledge - treats (non)-nullable parameters accordingly.

2024-03-19 08:33 UTC, declantsien commented on glutin/src/api/egl/config.rs
> +                        if xcb.visual_id.is_some() && xcb.visual_id.unwrap().get() > 0 =>
If I understand correctly
Compare `xcb.visual_id` with `config.native_visual` when `xcb.visual.id > 0`,
anyother case return false.

2024-03-19 08:34 UTC, declantsien commented on glutin/src/api/egl/display.rs
> +                (egl::PLATFORM_X11_KHR, handle.display.unwrap().as_ptr())
Ok return `ptr::null_mut()` if None

2024-03-19 08:41 UTC, declantsien commented on glutin/src/api/glx/display.rs
> +                (GlxDisplay(handle.display.unwrap().as_ptr() as *mut _), handle.screen as i32)
I can't make `if let else` working here. We are setting inline variable here.
Anyway hopes `match` fits here.

2024-03-19 10:17 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +                    handle.display.map(|d| d.as_ptr()).unwrap_or(ptr::null_mut()),
There's a check below that turns this into `egl::DEFAULT_DISPLAY` (whose value is `0`) but it's also set explicitly in Android :)

(Maybe this section of code needs some cleanup to read more logically)

2024-03-19 10:17 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +            },
It might be cleaner to write this `unwrap()` as an explicit `Some` match:

```suggestion
            RawDisplayHandle::Xlib(XlibDisplayHandle { display: Some(display), .. }) => {
                display.as_ptr()
            },
```

2024-03-19 10:17 UTC, MarijnS95 commented on glutin/src/api/egl/surface.rs
>                  }
Isn't this a `NonZeroU32`? This check makes no sense.

```suggestion
```

2024-03-19 10:17 UTC, MarijnS95 commented on glutin_examples/src/lib.rs
> +        .and_then(|window| window.window_handle().map(|handle| handle.as_raw()).ok());
Same here.

2024-03-19 10:17 UTC, MarijnS95 commented on glutin_examples/src/lib.rs
> +                    Err(err) => panic!("Error: {err:?}"),
Same here, even though it's just an example.

2024-03-19 10:17 UTC, MarijnS95 commented on glutin/src/api/egl/config.rs
> +                        .map(|id| id > 0 && id == config.native_visual())
This is already a `NonZeroU32` (otherwise `visual_id` is `None`)

2024-03-19 11:59 UTC, declantsien commented on glutin/src/api/egl/display.rs
> +                    handle.display.map(|d| d.as_ptr()).unwrap_or(ptr::null_mut()),
> There's a check below that turns this into egl::DEFAULT_DISPLAY (whose value is 0) but it's also set explicitly in Android :)

[AndroidDisplayHandle](https://docs.rs/raw-window-handle/latest/raw_window_handle/struct.AndroidDisplayHandle.html) is empty, not sure what are you asking for...

2024-03-19 12:05 UTC, declantsien commented on glutin_examples/src/lib.rs
> +                    Err(err) => panic!("Error: {err:?}"),
Nah, this will not. I saw an `unwrap()` just above the line. It's inside the closure for `event_loop`

2024-04-14 13:59 UTC, sarthakvk commented
Is there a plan to merge this PR?

2024-04-14 18:28 UTC, kchibisov commented
In general, re-request the review with github UI when it's ready or explicitly indicate the state if you're not interested anymore.

2024-04-18 18:05 UTC, kchibisov approved these changes

2024-05-05 16:33 UTC, MarijnS95 reviewed
Overall seeing a bit too many semantical changes that I'm not immediately content with. `raw-window-handle 0.6` gives us the ability to know that values are intentionally `0`/`null()` by setting an `Option` to `None`, but we're not taking this opportunity to validate whether the underlying API can and should handle that value, or that we should bail. In some cases there are unwraps, or `None` propagation, or `?` propagation making things harder to follow and validate.

2024-05-05 16:33 UTC, MarijnS95 commented on glutin-winit/src/lib.rs
> +    unsafe { Ok(Display::new(handle.as_raw(), _preference)?) }
Nit: `let handle` is different here than in `build_surface_attributes()`.

2024-05-05 16:33 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +            RawDisplayHandle::Xlib(XlibDisplayHandle { display: Some(d), .. }) => d.as_ptr(),
Previously setting `display` to `null`/`None` would cause `egl::DEFAULT_DISPLAY` to be used below, now this causes it to return `NotSupported`?

If there's an explicit case to be made that no default display exists for `Xlib`, that should be documented as the previous code was allowing this.

2024-05-05 16:33 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +                    handle.display.map(|d| d.as_ptr()).unwrap_or(ptr::null_mut()),
Asking to make the code flow less silly/hard-to-read.

2024-05-05 16:33 UTC, MarijnS95 commented on glutin/src/api/wgl/display.rs
> +                        window.hinstance.map(|i| i.get()).unwrap_or(0) as _,
`unwrap_or_else`?

I'm unfamiliar with this code to say if it's okay to pass `0` for `HINSTANCE`. There are multiple getters but don't know if any should be used.

2024-05-05 16:33 UTC, MarijnS95 commented on glutin_examples/examples/switch_render_thread.rs
> +        Err(err) => panic!("Error {err:?}"),
That's equivalent to `.expect("Error")` (except that you don't expect there to be an error, but a more sensible message).

2024-05-05 16:33 UTC, MarijnS95 commented on glutin_examples/src/lib.rs
> +                    Err(err) => panic!("Error: {err:?}"),
Then make it a proper `.expect()` with a clear message.

2024-05-05 18:00 UTC, kchibisov commented on glutin/src/api/wgl/display.rs
> +                        window.hinstance.map(|i| i.get()).unwrap_or(0) as _,
it's the same as before, because it could be 0, which is default for rwh 0.5 and lower.

2024-05-06 01:09 UTC, declantsien commented on glutin/src/api/egl/display.rs
> +            RawDisplayHandle::Xlib(XlibDisplayHandle { display: Some(d), .. }) => d.as_ptr(),
Nice catch

2024-05-06 01:13 UTC, declantsien commented
@kchibisov Can you help with the CI error. Wired cfg errors.

2024-05-06 02:07 UTC, declantsien commented
> @kchibisov Can you help with the CI error. Wired cfg errors.

The error is from the rust nightly. Tried with an old build `nightly-2024-04-05` the errors are gone. Since we don't have a `rust-toolchain.toml` file, no idea how to deal with it.
Another question, why don't we use Cargo.lock? Cargo.lock is useful for reproducible build.

2024-05-06 05:10 UTC, kchibisov commented
>Another question, why don't we use Cargo.lock? Cargo.lock is useful for reproducible build.

The old default behavior for rust was to not include `Cargo.lock` for libraries. They changed that to include last year iirc.

2024-05-06 05:27 UTC, kchibisov approved these changes
Should be good after rebase.

2024-05-06 07:36 UTC, declantsien commented
> Should be good after rebase.

Nice

2024-05-06 07:37 UTC, declantsien commented
> > Another question, why don't we use Cargo.lock? Cargo.lock is useful for reproducible build.
> 
> The old default behavior for rust was to not include `Cargo.lock` for libraries. They changed that to include last year iirc.

Right. Good to know. Thanks.

2024-05-06 07:57 UTC, MarijnS95 commented
> Another question, why don't we use Cargo.lock? Cargo.lock is useful for reproducible build.

A reproducible build (for libraries) is "useless" when a published crate is on crates.io. Only semver version (range) dependencies from `Cargo.toml` are taken into account when your crate is used in another project. `cargo` doesn't magically "merge" its `Cargo.lock` with the lockfile of the current project:

https://doc.rust-lang.org/cargo/faq.html#:~:text=However%2C%20this%20determinism%20can%20give%20a%20false%20sense%20of%20security%20because%20Cargo.lock%20does%20not%20affect%20the%20consumers%20of%20your%20package%2C%20only%20Cargo.toml%20does%20that.

2024-05-06 07:58 UTC, MarijnS95 commented on CHANGELOG.md
> +- **Breaking:** updated `raw-window-handle` dependency to `0.6.1`.
Question for @kchibisov: the changelog seems to have a mix of past- and present-tense. What should we pick?

2024-05-06 07:59 UTC, MarijnS95 commented on glutin-winit/Cargo.toml
> +raw-window-handle = "0.6.1"
Is there anything new in the `0.6.1` release that is not in the `0.6.0` release, that is required by `glutin`?

2024-05-06 08:03 UTC, MarijnS95 approved these changes
One more cleanup request for an unreachable `if display.is_null()`, but seems like we're getting somewhere otherwise.

2024-05-06 08:03 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +                display.map_or(egl::DEFAULT_DISPLAY as *mut _, |d| d.as_ptr())
Fwiw I meant to just map it to `null()` since this special value is selected below if it was `is_null()`.

2024-05-06 08:03 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +                display.map_or(egl::DEFAULT_DISPLAY as *mut _, |d| d.as_ptr())
But then Android could have done the same. As said in earlier review, this function is a tad messy.

2024-05-06 08:03 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +                display.map_or(egl::DEFAULT_DISPLAY as *mut _, |d| d.as_ptr())
In fact, since `gbm_device` is `NonNull`, I'd request to remove the now-unreachable thing below:

```rust
        if display.is_null() {
            display = egl::DEFAULT_DISPLAY as *mut _;
        }
```

2024-05-06 08:07 UTC, MarijnS95 commented on glutin/src/api/wgl/display.rs
> +                        window.hinstance.map(|i| i.get()).unwrap_or(0) as _,
@kchibisov yes that is the point: it could have been passed before, but now that we _know_ the `raw-window-handle` API _allows zero_, we should take a second to realize whether that is actually an allowed case.

2024-05-06 08:09 UTC, MarijnS95 commented on glutin/src/api/wgl/display.rs
> +                        window.hinstance.map(|i| i.get()).unwrap_or(0) as _,
_Our own_ safety docs already say that this must be "valid":

https://github.com/rust-windowing/glutin/blob/052399de0a4a7237b4dc12dd0fcdeb63f1c2af41/glutin/src/api/wgl/display.rs#L40-L44

So I think this should be a `panic!()`/`.unwrap()`/`ok_or...()?`.

2024-05-06 08:11 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> -            display = egl::DEFAULT_DISPLAY as *mut _;
Not this one, unless you change all the `.map_or()`'s above to return `egl::DEFAULT_DISPLAY` instead.

2024-05-06 08:23 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +                display.map_or(std::ptr::null(), |d| d.as_ptr())
:shrug: 

```suggestion
                display.map_or(egl::DEFAULT_DISPLAY as *mut _, |d| d.as_ptr())
```

2024-05-06 08:24 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +                (egl::PLATFORM_X11_EXT, handle.display.map_or(ptr::null_mut(), |d| d.as_ptr()))
`if display.is_null()` can be removed if you set `egl::DEFAULT_DISPLAY as *mut _` here... 1/2

2024-05-06 08:24 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +                (egl::PLATFORM_XCB_EXT, handle.connection.map_or(ptr::null_mut(), |c| c.as_ptr()))
And `egl::DEFAULT_DISPLAY as *mut _` here 2/2.

2024-05-06 08:37 UTC, MarijnS95 commented
One item remaining, the rest looks good:

- https://github.com/rust-windowing/glutin/pull/1670#discussion_r1590681604

2024-05-06 10:31 UTC, declantsien commented on glutin/src/api/wgl/display.rs
> +                        window.hinstance.map(|i| i.get()).unwrap_or(0) as _,
> So I think this should be a `panic!()`/`.unwrap()`/`ok_or...()?`.

I go with `.unwrap()`.

2024-05-06 10:33 UTC, declantsien commented
> One item remaining, the rest looks good:
> 
>     * [Update `raw-window-handle` to v0.6 #1670 (comment)](https://github.com/rust-windowing/glutin/pull/1670#discussion_r1590681604)

@MarijnS95 I think I am done with your requests.

2024-05-21 08:17 UTC, MarijnS95 commented on glutin/src/api/wgl/display.rs
> +                        window.hinstance.map(|i| i.get()).unwrap_or(0) as _,
Yes that is a good idea. If people were previously implicitly passing `0` (mismatching the `# Safety` docs), we'll catch that and can always amend the code with a new patch release.

2024-05-21 16:05 UTC, merged

2024-05-25 17:05 UTC, marc2332 commented on glutin_examples/Cargo.toml
>  winit = { version = "0.29.2", default-features = false, features = ["rwh_05"] }
Any reason this version of `winit` was left unchanged with `rwh_05` instead of `rwh_06` ?

I just noticed it when resolving conflicts in https://github.com/rust-windowing/glutin/pull/1675

2024-05-25 17:09 UTC, kchibisov commented on glutin_examples/Cargo.toml
>  winit = { version = "0.29.2", default-features = false, features = ["rwh_05"] }
it's example, doesn't really matter. Could use 06.

2024-05-25 17:10 UTC, marc2332 commented on glutin_examples/Cargo.toml
>  winit = { version = "0.29.2", default-features = false, features = ["rwh_05"] }
Yeah, seems to work just fine, I simply found it odd 😄