Fix logic in egl Device::query_device
rust-windowing/glutin pull request #1686
Opened 2024-07-01 19:28 UTC by quaternic

The previous test would mistakenly return an error if the extensions contain "EGL_EXT_device_base" but not the two others. As stated by the comment, and in https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_device_base.txt , it is supposed to contain the other two.

The cases that should not return an error are:
 - contains EGL_EXT_device_base
 - contains both EGL_EXT_device_enumeration and EGL_EXT_device_query

2024-07-03 17:57 UTC, kchibisov commented
cc @i509VCB I think the test was similar to the one in smithay?

2024-07-03 18:57 UTC, kchibisov requested changes
Should add a CHANGELOG entry.

2024-07-03 19:02 UTC, i509VCB commented
> The previous test would mistakenly return an error if the extensions contain "EGL_EXT_device_base" but not the two others. As stated by the comment, and in https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_device_base.txt , it is supposed to contain the other two.
>
> The cases that should not return an error are:
> 
> * contains EGL_EXT_device_base
> * contains both EGL_EXT_device_enumeration and EGL_EXT_device_query

The changes look correct the specification for EGL_EXT_device_base states the following:

```
Add to section "3.2 Devices"

    "EGL_EXT_device_base is equivalent to the combination of the
    functionality defined by EGL_EXT_device_query and
    EGL_EXT_device_enumeration."
```

2024-07-03 19:05 UTC, i509VCB commented on glutin/src/api/egl/device.rs
>              return Err(ErrorKind::NotSupported("EGL does not support EGL_EXT_device_base").into());
This error is not correct, maybe just say enumerating/querying devices is unsupported.

2024-07-03 20:11 UTC, quaternic commented on glutin/src/api/egl/device.rs
>              return Err(ErrorKind::NotSupported("EGL does not support EGL_EXT_device_base").into());
It seems that `EGL_EXT_device_enumeration` actually requires `EGL_EXT_device_query`, so I believe this code doesn't need to check for the latter at all.

2024-07-03 20:14 UTC, kchibisov commented on glutin/src/api/egl/device.rs
>              return Err(ErrorKind::NotSupported("EGL does not support EGL_EXT_device_base").into());
it's better to check just _in case_, like it could be redundant, but some drivers may have bugs.

2024-07-03 20:48 UTC, quaternic commented on glutin/src/api/egl/device.rs
>              return Err(ErrorKind::NotSupported("EGL does not support EGL_EXT_device_base").into());
So, that would be a driver that claims to support `EGL_EXT_device_enumeration` but actually doesn't. I suppose it makes sense to check for that and report it as a bug in the driver.

2024-07-03 21:11 UTC, kchibisov commented on glutin/src/api/egl/device.rs
>              return Err(ErrorKind::NotSupported("EGL does not support EGL_EXT_device_base").into());
It could also be a _middle layer_ bug, like if something breaks in `libglvnd` because it also has to wire everything...

2024-07-03 21:23 UTC, quaternic commented on glutin/src/api/egl/device.rs
>              return Err(ErrorKind::NotSupported("EGL does not support EGL_EXT_device_base").into());
Oh, yeah. I'll make that case return an error with a different message. Would panicking in debug mode make sense?

2024-07-03 22:26 UTC, kchibisov commented on glutin/src/api/egl/device.rs
>              return Err(ErrorKind::NotSupported("EGL does not support EGL_EXT_device_base").into());
Library should really not panic and just propagate.

2024-07-04 07:48 UTC, MarijnS95 reviewed
Nice catch, the original logic doesn't match what's described in the comment :)

2024-07-04 07:48 UTC, MarijnS95 commented on glutin/src/api/egl/device.rs
> +                    "enumerating devices is not supported by the EGL instance"
```suggestion
                    "Enumerating devices is not supported by the EGL instance"
```

2024-07-04 07:48 UTC, MarijnS95 commented on glutin/src/api/egl/device.rs
> +        // The former depends on EGL_EXT_device_query, so also check that just in case.
For readability (especially inside this diff), perhaps this last line of comment belongs _inside_ the `if`?

2024-07-05 09:59 UTC, kchibisov commented on glutin/src/api/egl/device.rs
> +            if !(query & enumr) {
```suggestion
            if !(query && enumr) {
```

2024-07-05 09:59 UTC, kchibisov commented on glutin/src/api/egl/device.rs
> +                    // this should not happen as device_enumeration depends on device_query
```suggestion
                    // This should not happen as device_enumeration depends on device_query.
```

2024-07-05 17:10 UTC, kchibisov approved these changes

2024-07-07 19:24 UTC, quaternic commented on glutin/src/api/egl/device.rs
> +        // The former depends on EGL_EXT_device_query, so also check that just in case.
Well, trying to reposition that comment led to also reorganizing the code, but I think it's better overall now.

2024-07-21 09:13 UTC, MarijnS95 approved these changes

2024-07-21 09:20 UTC, merged