Fix EglGetProcAddress crash on win32-x86
rust-windowing/glutin pull request #1688
Opened 2024-08-08 02:21 UTC by varphone

- [x] Tested on all platforms changed
- [ ] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

# Summary

Change the calling convention of the `EglGetProcAddress` declaration to `extern "system"` to automatically use the correct calling convention for the platform.

# Details

The `EglGetProcAddress` function uses the `stdcall` calling convention on the `Win32-x86` platform, but it was previously declared as `extern "C"` in the code.

On the `Win32-x86` platform, `extern "C"` functions use the `cdecl` calling convention by default.

This mismatch in calling conventions caused a crash.

By changing the declaration to `extern "system"`, the correct calling convention for the platform will be used automatically, preventing the crash.

# Testing

- Verified that the application no longer crashes on the `Win32-x86` platform.
- Ensured that the change does not affect other platforms.

2024-08-09 19:05 UTC, kchibisov requested changes
Could you add a changelog entry for that? should be fine after that.

2024-08-10 09:06 UTC, varphone commented
> Could you add a changelog entry for that? should be fine after that.

Already added, please review again.

2024-08-10 09:09 UTC, MarijnS95 commented
In general I'm not a fan of "Fixed crash" or other context-less titles using the word "fix", can we come up with anything more descriptive (i.e. _"use the correct calling convention for `EglGetProcAddress()` on Win32-x86 (optionally: preventing a crash)"_)? Same for the PR title.

Probably not a requirement to merge though, depending on what Kirill thinks of this.

2024-08-23 11:53 UTC, kchibisov requested changes
Should be fine after that.

2024-08-23 11:53 UTC, kchibisov commented on CHANGELOG.md
> +- Fixed crash in `EglGetProcAddress` on Win32-x86 platform
```suggestion
- Fixed crash in `EglGetProcAddress` on Win32-x86 platform due to wrong calling convention
```

2024-08-26 11:37 UTC, kchibisov approved these changes

2024-08-26 11:37 UTC, merged