Patch the `libglvnd` aliasing issue for EGL.
rust-windowing/glutin pull request #1690
Opened 2024-08-26 13:31 UTC by janKilika

See issue #1689 for further details.

The only actual change is that it is checked in `Display::initialize_display` with the `Display::sanitize_libglvnd_aliasing` function whether (a) `EglDisplay` is of variant `Khr` and (b) version is equal to 1.4, and if both conditions are true, `EglDisplay` is downgraded from `Khr` to `Ext`. This seems to be safe, as `eglGetPlatformDisplay` and `eglGetPlatformDisplayEXT` in practice are made to be aliases of each other by `libglvnd`, and if any of the attributes passed are invalid for the underlying function, it is presumed that it would return with an error.

2024-08-26 13:55 UTC, MarijnS95 reviewed
We can probably fit a more descriptive title than "aliasing issue" without going over any character limit.

2024-08-26 13:55 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +            // libglvnd has an unsavoury quirk of aliasing `getPlatformDisplay` and
Can you link the source code that describes this "unsavoury quirk", and how it's gone in 1.5?

2024-08-26 14:00 UTC, janKilika commented on glutin/src/api/egl/display.rs
> +            // libglvnd has an unsavoury quirk of aliasing `getPlatformDisplay` and
[Relevant portion here](https://gitlab.freedesktop.org/glvnd/libglvnd/-/blob/master/src/EGL/libegl.c#L270-358). `libglvnd` uses the same underlying function of `GetPlatformDisplayCommon` for both of the aliased functions. Although it passes a parameter [`funcName`](https://gitlab.freedesktop.org/glvnd/libglvnd/-/blob/master/src/EGL/libegl.c#L272) to it with the name of the function that called `GetPlatformDisplayCommon`, it only uses it for error reporting.

2024-08-26 14:47 UTC, janKilika commented on glutin/src/api/egl/display.rs
> +            // libglvnd has an unsavoury quirk of aliasing `getPlatformDisplay` and
Also of note is [this comment](https://gitlab.freedesktop.org/glvnd/libglvnd/-/blob/master/include/glvnd/libeglabi.h#L231-232) for `getPlatformDisplay` field of `__EGLapiImports`.

2024-08-26 15:04 UTC, janKilika commented on glutin/src/api/egl/display.rs
> +            // libglvnd has an unsavoury quirk of aliasing `getPlatformDisplay` and
> and how it's gone in 1.5?

As for the problem not being relevant for EGL 1.5, it's because `Khr` displays are actually valid for 1.5 platforms, which means KHR platform functions (i.e. `eglCreatePlatform`..`Surface` functions) won't subsequently crash with `BadDisplay`. For 1.4 platforms, these functions cannot be used, as they error out with `BadDisplay` when provided with a display that was returned by the aliased function; EXT platform functions must be used instead (i.e. `eglCreatePlatform`..`SurfaceEXT`).

2024-09-02 10:07 UTC, kchibisov requested changes
Also need a changelog entry for this.

2024-09-02 10:07 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +            (EglDisplay::Khr(display), Version { major: 1, minor: 4 }) => EglDisplay::Ext(display),
I was thinking to ensure that the function pointers for `egl.GetPlatformDisplay` and `egl.GetPlatformDisplayExt` are the same before doing such thing, so you can ensure that the cast is _safe_ because the same functions were used to produce the pointer.

Just doing a raw cast might be not a great idea if the functions are _different_?

2024-09-02 10:39 UTC, janKilika commented on glutin/src/api/egl/display.rs
> +            (EglDisplay::Khr(display), Version { major: 1, minor: 4 }) => EglDisplay::Ext(display),
> I was thinking to ensure that the function pointers for `egl.GetPlatformDisplay` and `egl.GetPlatformDisplayExt` are the same before doing such thing, so you can ensure that the cast is _safe_ because the same functions were used to produce the pointer.

The problem with that is that they are only aliased by `libglvnd` internally. The functions requested through the dynamic library are technically distinct, but otherwise call the same underlying vendor function.

> Just doing a raw cast might be not a great idea if the functions are different?

I'd say that considering the version is explicitly checked here to be 1.4 before the downgrade, this isn't much of a problem per `libglvnd`'s aliasing and the fact that `EglDisplay::Khr` shouldn't even be possible for 1.4. Although, I suppose this could cause EGL to error out at surface creation if `EGL_EXT_platform_base` isn't actually available for the platform, but that hinges on the KHR display connection request not failing beforehand, and I'm not entirely sure how that would play out when the underlying vendor function is `eglGetDisplay` or whether that's even possible.

2024-09-02 10:48 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +            (EglDisplay::Khr(display), Version { major: 1, minor: 4 }) => EglDisplay::Ext(display),
>The problem with that is that they are only aliased by libglvnd internally. The functions requested through the dynamic library are technically distinct, but otherwise call the same underlying vendor function.

We can not assume that, if pointers are different then we not do a casting since they could in fact be different. The problem is that libglvnd tells us that 1.5 exists due to one vendor providing it, while it's not due to issue in how it's done in libglvnd. When using only a vendor library you won't ever have this issue in the first place from what I understand.

So, ensure the pointers are the same and that's the only time we can do such a cast safely.

2024-09-02 11:20 UTC, janKilika commented on glutin/src/api/egl/display.rs
> +            (EglDisplay::Khr(display), Version { major: 1, minor: 4 }) => EglDisplay::Ext(display),
> We can not assume that, if pointers are different then we not do a casting since they could in fact be different.

`libglvnd`'s public functions, the functions that are actually used through the dynamic library, are distinct (as the aliasing is only done internally in `libglvnd`; the public functions call the same underlying vendor function), so the check would inevitably fail and the downgrade wouldn't happen.

> When using only a vendor library you won't ever have this issue in the first place from what I understand.

Likely not, as vendor libraries would, I presume, only have the functions that are relevant to them.

> The problem is that libglvnd tells us that 1.5 exists due to one vendor providing it

Well, not quite. Firstly, `libglvnd` advertises client extensions if at least one implementation supports them, so fully discriminating based on them is out of the question. Secondly, `eglGetPlatformDisplay` and `eglGetPlatformDisplayEXT` are functions that exist in `libglvnd` and are loaded regardless of whether any of the platforms support them, and both internally call the same underlying vendor function, so fully discriminating based on whether they are loaded is also out of the question for `libglvnd`. If the display creation manages to succeed, we are basically only left to do a check for the version after display initialization, which the PR already introduces.

2024-09-02 11:23 UTC, janKilika commented
> Also need a changelog entry for this.

Done!

2024-09-02 11:36 UTC, kchibisov requested changes

2024-09-02 11:36 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +            (EglDisplay::Khr(display), Version { major: 1, minor: 4 }) => EglDisplay::Ext(display),
Hm, indeed they'll be different. I was thinking they just provide the same pointer when loading but no, they use different pointers but call to the same implementation.

In this case, I'd suggest to this only for `#[cfg(free_unix)]`.

I'll also open an issue upstream.

2024-09-02 11:36 UTC, kchibisov commented on CHANGELOG.md
> +- Fixed EGL's `Display::new` making an `EGLDisplay::Khr` when the underlying platform only supports `EGLDisplay::Ext` due to `libglvnd` using the same vendor functions for obtaining a display connect
That's not really a fix, it's a _workaround_, since it's a libglvnd bug, obviously.

2024-09-02 11:44 UTC, MarijnS95 commented on CHANGELOG.md
> +- Fixed EGL's `Display::new` making an `EGLDisplay::Khr` when the underlying platform only supports `EGLDisplay::Ext` due to `libglvnd` using the same vendor functions for obtaining a display connect
And the same applies to the PR & commit title which also need to be improved, as requested before.

2024-09-02 11:49 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +            // libglvnd has an unsavoury quirk of aliasing `getPlatformDisplay` and
Let's make these permalinks so that they keep referencing the same lines of code: https://gitlab.freedesktop.org/glvnd/libglvnd/-/blob/606f6627cf481ee6dcb32387edc010c502cdf38b/src/EGL/libegl.c#L270-358.

And the request is to provide this information within the code comment, so that folks don't have to go find this discussion thread on a PR via git blame.

2024-09-02 11:57 UTC, MarijnS95 commented
https://registry.khronos.org/EGL/sdk/docs/man/html/eglQueryString.xhtml

It's unfortunate that we cannot use `eglQueryString` with `NO_DISPLAY` to "supposedly" (?) read the EGL version before calling `eglInitialize()`, until version 1.5? It's unclear to me if that version requirement applies to `EGL_EXTENSIONS` because that's the only query listed to support `NO_DISPLAY` - but it would mean our call is invalid on your given `libglvnd` too?

2024-09-02 12:06 UTC, MarijnS95 commented
Reading somewhat further, we don't ever check if https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_client_extensions.txt works and following that, https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_platform_base.txt is available before calling `eglGetPlatformDisplayEXT()`?

2024-09-02 12:11 UTC, janKilika commented
> https://registry.khronos.org/EGL/sdk/docs/man/html/eglQueryString.xhtml
> 
> It's unfortunate that we cannot use `eglQueryString` with `NO_DISPLAY` to "supposedly" (?) read the EGL version before calling `eglInitialize()`, until version 1.5? It's unclear to me if that version requirement applies to `EGL_EXTENSIONS` because that's the only query listed to support `NO_DISPLAY` - but it would mean our call is invalid on your given `libglvnd` too?

If by call you mean querying the client extensions, then, as far I can see, `libglvnd` provides querying for client extensions through `eglQueryString` (the function exists in `libglvnd` and [specifically checks](https://gitlab.freedesktop.org/glvnd/libglvnd/-/blob/master/src/EGL/libegl.c#L925) for `NO_DISPLAY`) in accord with both the 1.5 specification and `EGL_EXT_client_extensions`, so the call is technically valid.

2024-09-02 12:20 UTC, MarijnS95 commented
Yes I mean us calling `eglQueryString` for `NO_DISPLAY`. According to https://registry.khronos.org/EGL/sdk/docs/man/html/eglQueryString.xhtml that's only supported from 1.5 onwards but `EGL_EXT_client_extensions` (which requires 1.4) specifies that it's possible as long you handle the `NULL`+`BAD_DISPLAY` case gracefully.

I was wondering if we could use something like that to detect and prevent the failure case from happening (by never calling `eglGetPlatformDisplay()`) but it seems like we have a chicken-egg problem here anyway by not knowing if we have a 1.5 display before calling functions that "rely on" knowing the version and/or extensions 😅 

---

Also, reading back the PR description, can you reword it to provide a summary of both the problem and proposed solution, rather than linking through to an 18-comment-dense issue thread "for further details"?

2024-09-02 12:24 UTC, MarijnS95 commented on CHANGELOG.md
> +- Implement a workaround for EGL's `Display::new` making an `EGLDisplay::Khr` when the underlying platform only supports `EGLDisplay::Ext` due to `libglvnd` using the same vendor functions for obtain
```suggestion
- Implement a workaround for EGL's `Display::new()` making an `EGLDisplay::Khr` when the underlying platform only supports `EGLDisplay::Ext` due to `libglvnd` using the same vendor functions for obtaining a display connection for both `eglGetPlatformDisplay()` and `eglGetPlatformDisplayEXT()`.
```

2024-09-02 12:24 UTC, kchibisov commented
Could also link to upstream issue I've just opened.

2024-09-02 12:33 UTC, janKilika commented
> Also, reading back the PR description, can you reword it to provide a summary of both the problem and proposed solution, rather than linking through to an 18-comment-dense issue thread "for further details"?

Sure, relevant information provided.

2024-09-02 12:39 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +            (EglDisplay::Khr(display), Version { major: 1, minor: 4 }) => EglDisplay::Ext(display),
Separate question: is EGL `1.3` or older something that even exists out in the wild and that `glutin` could possibly run on (via `libglvnd`)? If so, should we do this?


```suggestion
            (EglDisplay::Khr(display), Version { major, minor }) if major <= 1 && minor <= 4 => EglDisplay::Ext(display),
```

2024-09-02 13:38 UTC, janKilika commented on glutin/src/api/egl/display.rs
> +            (EglDisplay::Khr(display), Version { major: 1, minor: 4 }) => EglDisplay::Ext(display),
> If so, should we do this?

Probably not, since [`EGL_EXT_platform_base`](https://registry.khronos.org/EGL/extensions/EXT/EGL_EXT_platform_base.txt), the extension that provides the functions for `Ext` displays, is said in the specification to require 1.4. Downgrading to `Legacy` if the version number is even lower than 1.4 could be done, but I'm not certain how 1.3 or older would behave in this situation.

2024-09-03 17:29 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +            (EglDisplay::Khr(display), Version { major: 1, minor: 4 }) => EglDisplay::Ext(display),
I'd call this `sanitize_egl_display_provider` and always converted `Khr` to `Ext` if the version is `1.4` and the `ext` extension is present. Otherwise downgrade to legacy.

For more context https://gitlab.freedesktop.org/glvnd/libglvnd/-/issues/251 and also add an explanation telling that they are all basically the same, since it's generally, a `EGLDisplay`.

2024-09-05 11:35 UTC, kchibisov requested changes
I hope that this is the last one.

2024-09-05 11:35 UTC, kchibisov commented on CHANGELOG.md
> +- Implement a workaround for EGL's `Display::new()` making an `EGLDisplay::Khr` when the underlying platform only supports `EGLDisplay::Ext` due to `libglvnd` using the same vendor functions for obta
```suggestion
- Fixed EGL's `Display::new()` making an `EGLDisplay::Khr` when the EGL version is below 1.4.
```

2024-09-05 11:35 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +        #[cfg(free_unix)]
```suggestion
        // Sanitize the display version.
```

2024-09-05 11:35 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +    #[cfg(free_unix)]
```suggestion
```

2024-09-05 11:35 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +            EglDisplay::Khr(display) if version == Version { major: 1, minor: 4 } => {
Shouldn't this be

```suggestion
            EglDisplay::Khr(display) if version <= Version { major: 1, minor: 4 } => {
```

2024-09-05 11:47 UTC, MarijnS95 commented on CHANGELOG.md
> +- Implement a workaround for EGL's `Display::new()` making an `EGLDisplay::Khr` when the underlying platform only supports `EGLDisplay::Ext` due to `libglvnd` using the same vendor functions for obta
@kchibisov can we correct that to `when the EGL version is 1.4 or lower`. Otherwise, when the `EGL version is below 1.4`?

2024-09-05 11:48 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +            // https://gitlab.freedesktop.org/glvnd/libglvnd/-/issues/251
Let's drop all this too and simplify/abbreviate it?

2024-09-05 11:49 UTC, kchibisov commented on CHANGELOG.md
> +- Implement a workaround for EGL's `Display::new()` making an `EGLDisplay::Khr` when the underlying platform only supports `EGLDisplay::Ext` due to `libglvnd` using the same vendor functions for obta
sure.

2024-09-05 11:51 UTC, MarijnS95 commented on glutin/src/api/egl/display.rs
> +        let display = Self::sanitize_egl_display_provider(display, version);
What if we do this directly in the tail of `get_platform_display()`? That should make the code a lot more compact since you can simply change the `.map(EglDisplay::Khr)` to use `Egl` when the version is lower.

We have an exact same `if-else` in `get_platform_display_ext()` already.

2024-09-05 11:55 UTC, kchibisov commented on glutin/src/api/egl/display.rs
> +        let display = Self::sanitize_egl_display_provider(display, version);
yeah, not a bad idea.

2024-09-09 17:40 UTC, kchibisov approved these changes

2024-09-10 14:51 UTC, merged