wgl: add support for pixel buffer surfaces
rust-windowing/glutin pull request #1701
Opened 2024-09-19 18:27 UTC by SK83RJOSH

- [x] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [x] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [x] ~Created or updated an example program if it would help users understand this functionality~

I didn't create an example, since this is standard functionality that was previously unexposed.

2024-09-22 02:16 UTC, kchibisov requested changes

2024-09-22 02:16 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +        unsafe {
Should use unsafe around the actual call to unsafe function.

2024-09-22 02:16 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +        };
we don't `let else` in general, use `match`.

2024-09-22 02:16 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +pub enum WGLSurface {
In general rust wants the `WglSurface` spelling. Also, this type should be defined below other types in this file.

2024-09-22 02:16 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +        attrs.push(0);
can use array of 3 zero init c_int, no need to allocate, also capacity should be 3, not 2, just fyi.

2024-09-22 02:16 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +                    if let Some(extra) = self.display.inner.wgl_extra {
In general, `pbuffer` can not be created without `wgl_extra` being present, so in here and in `drop` you can `unwrap`.

2024-09-22 02:16 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +    unsafe fn raw_attribute(&self, attr: GLenum) -> c_int {
I don't think that this function is unsafe by any means? Like if you pass wrong attribute it'll just return err or zero iirc.

2024-09-22 02:16 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +                        extra.QueryPbufferARB(hbuf, attr as _, &mut value);
you should check whether the function actually succeeded.

2024-09-22 02:16 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +                let hdc = extra.GetPbufferDCARB(hbuf);
You should ensure that the create succeeded.

See https://registry.khronos.org/OpenGL/extensions/ARB/WGL_ARB_pbuffer.txt
on how error is propagated and detected. The same for query function you're using.

2024-09-22 03:15 UTC, SK83RJOSH commented on glutin/src/api/wgl/surface.rs
> +    unsafe fn raw_attribute(&self, attr: GLenum) -> c_int {
Perhaps not, I just noticed a trend that most `raw_attribute` helpers were marked as unsafe and continued the trend. Will fix this up though, as I agree, it doesn't make much sense. 🙂

2024-09-22 03:20 UTC, SK83RJOSH commented on glutin/src/api/wgl/surface.rs
> +    PBuffer(HPBUFFEREXT, wgl_extra::types::HDC),
Do you mean in that they both likely point to the same device context? Or that the types should be the same? 🙂

2024-09-22 03:42 UTC, SK83RJOSH commented on glutin/src/api/wgl/surface.rs
> +    PBuffer(HPBUFFEREXT, wgl_extra::types::HDC),
Going to assume you meant the type definitions as say, unfortunately, they are not; one is defined as `void*` and the other `unsigned int` - but I suppose it's OK to treat them as the same in the interest of making things a bit cleaner.

2024-09-22 03:59 UTC, SK83RJOSH commented on glutin/src/api/wgl/surface.rs
> +                    if let Some(extra) = self.display.inner.wgl_extra {
Indeed, I'm assuming it's okay to `.unwrap` inside of `Surface::raw_attribute` as well, in that case?

2024-09-22 11:32 UTC, kchibisov requested changes

2024-09-22 11:32 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +        };
you can use the old logic like with `vec` and assign. Should be cleaner.

```rust
let mut attrs = [0; 3];
if surface_attributes.largest_pbuffer {
    attrs[0] = wgl_extra::PBUFFER_LARGEST_ARB;
    attrs[1] = 1;
}
```

2024-09-22 11:32 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +            WglSurface::PBuffer(..) => RawSurface::Wgl(0 as _),
returning `zero` pointer just looks wrong. I think it should be the `HPBUFFEREXT` here?

2024-09-22 11:32 UTC, kchibisov commented on glutin/src/api/wgl/context.rs
> +            };
you can use your `hdc()` method here.

2024-09-22 11:49 UTC, SK83RJOSH commented on glutin/src/api/wgl/surface.rs
> +        };
That was my first pass ironically, though the let was a bit cleaner since it keeps attrs const, but will address now 🙂

2024-09-22 11:50 UTC, SK83RJOSH commented on glutin/src/api/wgl/surface.rs
> +            WglSurface::PBuffer(..) => RawSurface::Wgl(0 as _),
I thought so too, but I was a bit worried that people might be relying on the old behavior, so returning null at least means there shouldn't be any breakage if people were being sane and checking validity of handles 🙂 

With that said, I can make that change if you'd like.

2024-09-22 11:50 UTC, SK83RJOSH commented on glutin/src/api/wgl/context.rs
> +            };
Nice catch, knew I missed something ^^

2024-09-22 11:54 UTC, kchibisov commented on glutin/src/api/wgl/surface.rs
> +            WglSurface::PBuffer(..) => RawSurface::Wgl(0 as _),
Returning `null` is not sane because you created an _object_ and user would expect a valid pointer, but they'll get `null`. You generally shouldn't null check an object you've created and know that is non null.

2024-09-22 11:58 UTC, SK83RJOSH commented on glutin/src/api/wgl/surface.rs
> +            WglSurface::PBuffer(..) => RawSurface::Wgl(0 as _),
I suppose it's ultimately a matter of taste, I lean towards being particularly defensive, especially with external libraries, and thus sanity check these sorts of things at every opportunity - but I'm happy to make the change regardless. Users can/should probably be expected to check the underlying surface type anyway, and no one will run into this change unless they opt-in to using the new functionality. 🙂

2024-09-22 13:25 UTC, kchibisov requested changes
Could you update doc here https://github.com/rust-windowing/glutin/blob/master/glutin/src/surface.rs#L522 with the pbuffer that could be present there?

Other than that looks good.

2024-09-22 13:43 UTC, SK83RJOSH commented
Done! Thank you for the thorough review, and my apologies for the sorry state of this initially. Have a great rest of your weekend. 🙂

2024-09-22 13:46 UTC, kchibisov commented on glutin/src/surface.rs
> +    /// Either an `HWND` or `HPBUFFEREXT` depending on `SurfaceType`.
You can [`SurfaceType`] link directly, so users can click on the link.

2024-09-22 13:48 UTC, SK83RJOSH commented on glutin/src/surface.rs
> +    /// Either an `HWND` or `HPBUFFEREXT` depending on `SurfaceType`.
TIL 😄

2024-09-22 13:57 UTC, kchibisov commented on glutin/src/surface.rs
> +    /// Either an `HWND` or `HPBUFFEREXT` depending on [`SurfaceType`].
```suggestion
    /// Either a `HWND` or `HPBUFFEREXT` depending on [`SurfaceType`].
```

sorry, I hope that's the last one.

2024-09-22 14:16 UTC, SK83RJOSH commented on glutin/src/surface.rs
> +    /// Either an `HWND` or `HPBUFFEREXT` depending on [`SurfaceType`].
This one is actually a point of contention - in American English the `h` in `haitch` is silent... thus my decision to use an here, as I'd pronounce it as "an aitch wind"... but this is not a hill I want to die on :)

2024-09-22 14:23 UTC, kchibisov commented on glutin/src/surface.rs
> +    /// Either an `HWND` or `HPBUFFEREXT` depending on [`SurfaceType`].
I mean, I know this rule, it's not silent here since it's an abbreviation and all syllables are pronounced as the should. `an` should be used when the `h` is like in `hour`, so not pronounced, here it's `hardware` iirc if you want to be more pedantic, but it's still pronounced.

2024-09-22 14:24 UTC, kchibisov approved these changes

2024-09-22 14:24 UTC, merged

2024-09-22 14:36 UTC, SK83RJOSH commented on glutin/src/surface.rs
> +    /// Either an `HWND` or `HPBUFFEREXT` depending on [`SurfaceType`].
Aye, you're correct that's how it *should* pronounced given it's an acronym/abbreviation - but I don't think I've ever heard anyone put emphasis on an `H` when it's not followed by a vowel.

Ultimately this is kind of a `gif` vs. `jif` thing (`gif` being "correct", yet the one to coin the moniker still insists it's `jif`) so it's not worth losing any sleep over. Down to personal taste, so as I said, not a hill worth dying on today. 😛

2024-09-22 14:51 UTC, kchibisov commented on glutin/src/surface.rs
> +    /// Either an `HWND` or `HPBUFFEREXT` depending on [`SurfaceType`].
I think `hardware`(`hard` in general) is a good example of it, since it's not `ardware` or `ard`.

2024-09-23 17:02 UTC, SK83RJOSH commented on glutin/src/surface.rs
> +    /// Either an `HWND` or `HPBUFFEREXT` depending on [`SurfaceType`].
https://learn.microsoft.com/en-us/windows/apps/develop/ui-input/retrieve-hwnd