feat: add openharmony support
rust-windowing/glutin pull request #1702
Opened 2024-09-21 01:54 UTC by richerfu

- [ ] Tested on all platforms changed
- [x] Added an entry to `CHANGELOG.md` if knowledge of this change could be valuable to users
- [ ] Updated documentation to reflect any user-facing changes, including notes of platform-specific behavior
- [ ] Created or updated an example program if it would help users understand this functionality

Add openharmony platform support, now we can build it successfully with [XComponent](https://developer.huawei.com/consumer/en/doc/harmonyos-guides-V5/napi-xcomponent-guidelines-V5). It doesn't effect any other code, so i think i needn't to add more docs or tests.

And you can find a full example with [example](https://github.com/ohos-rs/ohos-native-bindings/tree/master/examples/xcomponent). If you want more info, please let me know, thanks !

2024-09-22 01:53 UTC, kchibisov requested changes
You should also explicitly set that we depend on `raw-window-handle 0.6.2`, since the build will break otherwise.

2024-09-22 01:53 UTC, kchibisov commented on CHANGELOG.md
> +- Add `OpenHarmony` platform support.
This will need a rebase, and state that it's for EGL.

2024-09-22 02:35 UTC, richerfu commented
> raw-window-handle

Should i update the `raw-window-handle` version to 0.6.2? Looks not..

2024-09-22 02:36 UTC, kchibisov commented
>Should i update the raw-window-handle version to 0.6.2? Looks not..

open harmony was added in 0.6.2, so you should explicitly specify 0.6.2

2024-09-22 02:39 UTC, richerfu commented
> > Should i update the raw-window-handle version to 0.6.2? Looks not..
> 
> open harmony was added in 0.6.2, so you should explicitly specify 0.6.2

Done

2024-09-22 02:44 UTC, kchibisov requested changes

2024-09-22 02:44 UTC, kchibisov commented on glutin-winit/Cargo.toml
> +raw-window-handle = "0.6.2"
You don't need to update it here.

2024-09-22 02:44 UTC, kchibisov commented on glutin_examples/Cargo.toml
> +raw-window-handle = "0.6.2"
Don't need to update here as well.

2024-09-22 03:31 UTC, richerfu commented on glutin_examples/Cargo.toml
> +raw-window-handle = "0.6.2"
Reverted

2024-09-22 11:22 UTC, kchibisov approved these changes

2024-09-22 11:23 UTC, merged

2024-09-23 09:07 UTC, MarijnS95 commented on glutin/build.rs
> +        ohos_platform: { target_env = "ohos" },
Glutin's CI is quite extensive. @richerfu would you be up for adding one or two `ohos` target triples to our CI with the `egl` feature, so that we can always build-test this functionality and make sure this target environment is not accidentally broken in the future?

2024-09-23 09:33 UTC, richerfu commented on glutin/build.rs
> +        ohos_platform: { target_env = "ohos" },
OpenHarmony currently has no environment to directly run `cargo test`, and all code testing is forcibly dependent on real machines. So there is no way to do some testing or verification in the CI environment for the time being. According to official news, this capability will be supported as early as Q1 2025.

2024-09-23 10:14 UTC, MarijnS95 commented on glutin/build.rs
> +        ohos_platform: { target_env = "ohos" },
@richerfu I don't think we need run-time tests, just build-testing (i.e. `cargo check/build/clippy`) is enough _for now_ to at least guarantee a minimum level of source compatibility. We can incrementally move towards testing on real machines _if that possibility is provided_.

For example, this works for me:

```console
$ rustup target add x86_64-unknown-linux-ohos
$ cargo clippy --all-features --target x86_64-unknown-linux-ohos -p glutin
```

And if I make a silly change, like commenting out a `Self::Ohos` `match` arm, the compiler/CI could complain that the `ohos` target no longer even compiles:

```console
$ cargo clippy --all-features --target x86_64-unknown-linux-ohos -p glutin
error[E0004]: non-exhaustive patterns: `api::egl::surface::NativeWindow::Ohos(_)` not covered
   --> glutin/src/api/egl/surface.rs:541:15
    |
541 |         match *self {
    |               ^^^^^ pattern `api::egl::surface::NativeWindow::Ohos(_)` not covered
    |
note: `api::egl::surface::NativeWindow` defined here
   --> glutin/src/api/egl/surface.rs:446:6
    |
446 | enum NativeWindow {
    |      ^^^^^^^^^^^^
...
460 |     Ohos(*mut ffi::c_void),
    |     ---- not covered
    = note: the matched value is of type `api::egl::surface::NativeWindow`
help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern or an explicit pattern as shown
    |
541 ~         match *self {
542 +             api::egl::surface::NativeWindow::Ohos(_) => todo!(),
543 +         }
    |

For more information about this error, try `rustc --explain E0004`.
error: could not compile `glutin` (lib) due to 1 previous error
```

2024-09-23 10:51 UTC, richerfu commented on glutin/build.rs
> +        ohos_platform: { target_env = "ohos" },
Ok, i'll try to add some code and upgrade CI config later.